force-app/main/default/objects/AR_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AR_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Charge_Code__c.field-meta.xml
<CustomField>
    <fullName>Charge_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge Code</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>AR_Charge_Code__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.CreatedDate</field>
            <operation>lessThan</operation>
            <value>5/20/2025, 12:00 AM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AR_Charge_Code__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Installment_Date__c.field-meta.xml
<CustomField>
    <fullName>Installment_Date__c</fullName>
    <label>Installment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Payment_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan Detail</label>
    <referenceTo>Payment_Plan_Detail__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Inventory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting for BD Approval</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Rejected by BD</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancellation in Progress</fullName>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Resale in Progress</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>DeMerged</fullName>
            </value>
            <value>
                <fullName>Under Termination</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Charge_Code__c.field-meta.xml
<CustomField>
    <fullName>Charge_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge Code</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>AR_Charge_Code__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.CreatedDate</field>
            <operation>lessThan</operation>
            <value>5/20/2025, 12:00 AM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AR_Charge_Code__c</referenceTo>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Installment_No__c.field-meta.xml
<CustomField>
    <fullName>Installment_No__c</fullName>
    <label>Installment No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN01</fullName>
                <label>in01</label>
            </value>
            <value>
                <fullName>IN02</fullName>
                <label>in02</label>
            </value>
            <value>
                <fullName>in03</fullName>
            </value>
            <value>
                <fullName>in04</fullName>
            </value>
            <value>
                <fullName>in05</fullName>
            </value>
            <value>
                <fullName>in06</fullName>
            </value>
            <value>
                <fullName>in07</fullName>
            </value>
            <value>
                <fullName>in08</fullName>
            </value>
            <value>
                <fullName>in09</fullName>
            </value>
            <value>
                <fullName>in10</fullName>
            </value>
            <value>
                <fullName>in11</fullName>
            </value>
            <value>
                <fullName>in12</fullName>
            </value>
            <value>
                <fullName>in13</fullName>
            </value>
            <value>
                <fullName>in14</fullName>
            </value>
            <value>
                <fullName>in15</fullName>
            </value>
            <value>
                <fullName>in16</fullName>
            </value>
            <value>
                <fullName>in17</fullName>
            </value>
            <value>
                <fullName>in18</fullName>
            </value>
            <value>
                <fullName>in19</fullName>
            </value>
            <value>
                <fullName>in20</fullName>
            </value>
            <value>
                <fullName>in21</fullName>
            </value>
            <value>
                <fullName>in22</fullName>
            </value>
            <value>
                <fullName>in23</fullName>
            </value>
            <value>
                <fullName>in24</fullName>
            </value>
            <value>
                <fullName>in25</fullName>
            </value>
            <value>
                <fullName>in26</fullName>
            </value>
            <value>
                <fullName>in27</fullName>
            </value>
            <value>
                <fullName>in28</fullName>
            </value>
            <value>
                <fullName>in29</fullName>
            </value>
            <value>
                <fullName>in30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Instalment_Type__c.field-meta.xml
<CustomField>
    <fullName>Instalment_Type__c</fullName>
    <label>Instalment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Date</fullName>
            </value>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Handover Event</fullName>
            </value>
            <value>
                <fullName>PHPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resale Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Plan_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Payment_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan Detail</label>
    <referenceTo>Payment_Plan_Detail__c</referenceTo>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Progressed</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>UnPaid</fullName>
                <isActive>false</isActive>
                <label>UnPaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentPlanDetailHelper.cls
/**********************************************************************************************
* @Author: Prajwal Tijare
* @Created Date: 12 Nov 2025
* @Description: Helper class for Payment_Plan_Detail__c trigger. 
*               This class is responsible for generating AR_Invoice__c records 
*               automatically whenever a Payment Plan Detail record’s status is updated to 'Progressed'.
**************************************************************************************************/
/*************************************************************************************************
@Version History
* Version      Date             Name         	Description
* 1.0          12NOV2025        Prajwal     Initial draft - Invoice generation on status change to 'Progressed'
**************************************************************************************************/
public class PaymentPlanDetailHelper {
    
    public static void generateInvoices(List<Payment_Plan_Detail__c> newList, Map<Id, Payment_Plan_Detail__c> oldMap) {
        List<AR_Invoice__c> newInvoiceList = new List<AR_Invoice__c>();
        
        for (Payment_Plan_Detail__c ppd : newList) {
            Payment_Plan_Detail__c oldRec = oldMap.get(ppd.Id);
            if (oldRec != null && ppd.Status__c != oldRec.Status__c && ppd.Status__c == 'Progressed') {
                
                AR_Invoice__c newInvoice = new AR_Invoice__c();
                newInvoice.Name = ppd.Installment_No__c;
                //newInvoice.Account__c = ppd.Account__c;
                newInvoice.Amount__c = ppd.Amount__c;
                newInvoice.Charge_Code__c = ppd.Charge_Code__c;
                newInvoice.Inventory__c = ppd.Inventory__c;
                newInvoice.Opportunity__c = ppd.Opportunity__c;
                newInvoice.Payment_Plan_Detail__c = ppd.Id;
                newInvoice.Status__c = 'Pending Payment';
                newInvoice.Charge_Type__c = 'Installments';
                
                if (ppd.Instalment_Type__c == 'Fixed Date') {
                    newInvoice.Invoice_Date__c = ppd.Cheque_Date__c;
                } else {
                    newInvoice.Invoice_Date__c = Date.today();
                }
                
                newInvoice.Installment_Date__c = ppd.Cheque_Date__c;
                newInvoiceList.add(newInvoice);
            }
        }
        
        if (!newInvoiceList.isEmpty()) {
            try {
                insert newInvoiceList;
            } catch (Exception e) {
                System.debug('Invoice insertion failed: ' + e.getMessage());
            }
        }
    }
}