force-app/main/default/objects/AR_Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Payment_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan Detail</label>
    <referenceTo>Payment_Plan_Detail__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_PPD_Installment_Progression_Event__e/fields/Billed__c.field-meta.xml
<CustomField>
    <fullName>Billed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_PPD_Installment_Progression_Event__e/fields/PaymentPlanDetailId__c.field-meta.xml
<CustomField>
    <fullName>PaymentPlanDetailId__c</fullName>
    <label>PaymentPlanDetailId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_PPD_Installment_Progression_Event__e/fields/PhaseDate__c.field-meta.xml
<CustomField>
    <fullName>PhaseDate__c</fullName>
    <label>PhaseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Final_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Due_Date__c</fullName>
    <formula>IF(TEXT( Instalment_Type__c ) == &apos;Fixed Date&apos;,  Cheque_Date__c ,
IF(TEXT( Instalment_Type__c ) == &apos;Handover Event&apos; &amp;&amp; !ISBLANK(Handover_Date__c) &amp;&amp; Cheque_Date__c &gt;= Handover_Date__c, Cheque_Date__c, 
IF(TEXT( Instalment_Type__c ) == &apos;Handover Event&apos; &amp;&amp; !ISBLANK(Handover_Date__c) &amp;&amp; Handover_Date__c &gt;= Cheque_Date__c, Handover_Date__c, 
IF(TEXT( Instalment_Type__c ) == &apos;Milestone&apos; &amp;&amp; !ISBLANK( Milestone_Completion_Date__c ) &amp;&amp; Cheque_Date__c &gt;= Milestone_Completion_Date__c, Cheque_Date__c,
IF(TEXT( Instalment_Type__c ) == &apos;Milestone&apos; &amp;&amp; !ISBLANK( Milestone_Completion_Date__c ) &amp;&amp; Milestone_Completion_Date__c &gt;= Cheque_Date__c, Milestone_Completion_Date__c,
null)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resale Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Plan_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Payment_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan Detail</label>
    <referenceTo>Payment_Plan_Detail__c</referenceTo>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Progressed</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>UnPaid</fullName>
                <isActive>false</isActive>
                <label>UnPaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AR_PPDInstallmentsAutoProgressBatch.cls
/**********************************************************************************************
* @Author: Prajwal Tijare
* @Created Date: 12 Nov 2025
* @Description: Used to auto progress fixed date installments on PPD records and scheduled from AR_PPDInstallmentsAutoProgressScheduler.
**************************************************************************************************/
/*************************************************************************************************
@Version History
* Version      Date             Name         	Description
* 1.0         12NOV2025        Prajwal      	  Draft 
**************************************************************************************************/

public class AR_PPDInstallmentsAutoProgressBatch implements Database.Batchable<SObject> {
    
    public AR_PPDInstallmentsAutoProgressBatch() {}
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date todayDate = Date.today();
        System.debug('todayDate: ' + todayDate);
        
        return Database.getQueryLocator([
            SELECT Id, Status__c, Final_Due_Date__c
            FROM Payment_Plan_Detail__c
            WHERE Final_Due_Date__c = :todayDate
            AND Status__c = 'Draft'
            AND Id NOT IN (SELECT Payment_Plan_Detail__c FROM AR_Invoice__c)
            AND Billed__c = false
            AND Opportunity__c != null
        ]);
    }
    
    
    public void execute(Database.BatchableContext bc, List<Payment_Plan_Detail__c> scope) {
        system.debug('scope '+scope.size());
        List<AR_PPD_Installment_Progression_Event__e> eventsToPublish = new List<AR_PPD_Installment_Progression_Event__e>();
        for (Payment_Plan_Detail__c record : scope) {
            AR_PPD_Installment_Progression_Event__e event = new AR_PPD_Installment_Progression_Event__e();
            event.PaymentPlanDetailId__c = record.Id;
            event.Status__c = 'Progressed';
            event.PhaseDate__c = System.today();
            event.Billed__c = true;
            
            if (Test.isRunningTest()) {
                event.PhaseDate__c = Date.Today().addDays(100000);
            }
            eventsToPublish.add(event);
        }
        if (!eventsToPublish.isEmpty()) {
            try {
                EventBus.publish(eventsToPublish);
                if (Test.isRunningTest()){
                    eventsToPublish[0].Id = null;
                }
            } catch (Exception e) {
                AR_PPD_Installment_Progression_Event__e errorEvent = new AR_PPD_Installment_Progression_Event__e();
                errorEvent.Error__c = e.getMessage();
                errorEvent.Status__c = 'PPD Progression Error:';
                eventsToPublish.add(errorEvent);
                EventBus.publish(eventsToPublish);
            }
        }
        
    }
    public void finish(Database.BatchableContext bc) {        
        System.debug('Batch completed successfully. All eligible records progressed.');
    }
}