force-app/main/default/objects/Case/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseAssignmentHelper.cls
public class CaseAssignmentHelper {

    public static void assignCases(List<Case> caseList) {

        Account genePointAccount;

        try {
            genePointAccount = [
                SELECT Id
                FROM Account
                WHERE Name = 'Akash Khairnar'
                LIMIT 1
            ];
        } catch (Exception e) {
            return;
        }

        if (genePointAccount == null) {
            return;
        }

        for (Case c : caseList) {
            c.AccountId = genePointAccount.Id;
        }
    }

    public static void createContactOnApproval(
    List<Case> newCases,
    Map<Id, Case> oldMap
){
    List<Contact> contactsToInsert = new List<Contact>();

    for(Case cs : newCases){

        Case oldCase = oldMap.get(cs.Id);

        if(
            cs.Approval_Status__c == 'Approved' &&
            oldCase.Approval_Status__c != 'Approved' &&
            cs.AccountId != null
        ){

            Contact con = new Contact(
                FirstName = cs.First_Name__c,
                LastName  = cs.Last_Name__c,
                Email     = cs.Email__c,
                Phone     = cs.Phone__c,
                AccountId = cs.AccountId
            );

            contactsToInsert.add(con);
        }
    }

    if(!contactsToInsert.isEmpty()){
        insert contactsToInsert;
    }
}
}