force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>To capture the Project Status Green or Red, created for Nexus migration</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Used to have field values as Off plan, Completed and Ready.</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Off Plan</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/classes/GetPicklistTypeFields.cls
public with sharing class GetPicklistTypeFields {
    @AuraEnabled(cacheable=true)
    public static List<String> getProjectTypeValues() {
        List<String> typeValues = new List<String>();
        Schema.DescribeFieldResult fieldResult = Project__c.Project_Type__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry picklistVal : picklistValues) {
            typeValues.add(picklistVal.getLabel());
        }
        system.debug('Project Type values'+typeValues);

        return typeValues;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getProjectStatusValues() {
        List<String> statusValues = new List<String>();
        Schema.DescribeFieldResult fieldResult = Project__c.Project_Status__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry picklistVal : picklistValues) {
            statusValues.add(picklistVal.getLabel());
        }
        system.debug('Project Type values'+statusValues);

        return statusValues;
    }
    @AuraEnabled(cacheable=true)
    public static List<String> getDependentPicklistValues(String parentFieldName, String selectedParentValue, String dependentFieldName) {
        List<String> dependentValues = new List<String>();
        String soql = 'SELECT ' + dependentFieldName + ' FROM Project__c WHERE ' + parentFieldName + ' = \'' + selectedParentValue + '\'';
        List<Project__c> records = Database.query(soql);
        system.debug('Project Type values'+records);
        List<String> sizeTypeValues = new List<String> ();
        for (Project__c record : records) {
            sizeTypeValues.add((String)record.get(dependentFieldName));
            system.debug('sizeTypeValues'+sizeTypeValues);
        }
        dependentValues.addAll(sizeTypeValues);
          system.debug('Project Type values'+dependentValues);
        return dependentValues;
    }
}