force-app/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>Project Address</description>
    <inlineHelpText>Enter Project Address</inlineHelpText>
    <label>Project Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Header__c.field-meta.xml
<CustomField>
    <fullName>Project_Header__c</fullName>
    <description>Project Header</description>
    <inlineHelpText>Enter Project Header</inlineHelpText>
    <label>Project Header</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Image__c.field-meta.xml
<CustomField>
    <fullName>Project_Image__c</fullName>
    <description>Add Project Image.</description>
    <inlineHelpText>Add Project Image.</inlineHelpText>
    <label>Project Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Location__c.field-meta.xml
<CustomField>
    <fullName>Project_Location__c</fullName>
    <description>Project Location</description>
    <inlineHelpText>Enter Project Location in Latitude and Longitude</inlineHelpText>
    <label>Project Location</label>
    <scale>3</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>To capture the Project Status Green or Red, created for Nexus migration</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Used to have field values as Off plan, Completed and Ready.</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Off Plan</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Size_Type__c.field-meta.xml
<CustomField>
    <fullName>Size_Type__c</fullName>
    <description>Size Type</description>
    <inlineHelpText>select Size Type</inlineHelpText>
    <label>Size Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Hospitality(Hotel,Motels,Resorts)</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>Bunglow</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Among Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/classes/displayProjectsController.cls
public with sharing class displayProjectsController {
    //Display All project Records
    @AuraEnabled(cacheable=true)
    public static List<Project__c> showProjects(){
        try {
        return[select Id,Name,Project_Description__c,Project_Image__c,Project_Header__c,Project_Location__c,Project_Address__c,Project_Status__c, Project_Type__c,Size_Type__c
               from Project__c ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProject(String recordId){
        String recId = recordId;
        try {
        return[select Id,Name,Project_Description__c,Project_Image__c,Project_Header__c,Project_Location__c,Project_Address__c,Project_Status__c, Project_Type__c,Size_Type__c
               from Project__c 
               where Id =: recId ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   
}