force-app/main/default/objects/Project__c/fields/Project_Header__c.field-meta.xml
<CustomField>
    <fullName>Project_Header__c</fullName>
    <description>Project Header</description>
    <inlineHelpText>Enter Project Header</inlineHelpText>
    <label>Project Header</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Location__c.field-meta.xml
<CustomField>
    <fullName>Project_Location__c</fullName>
    <description>Project Location</description>
    <inlineHelpText>Enter Project Location in Latitude and Longitude</inlineHelpText>
    <label>Project Location</label>
    <scale>3</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>To capture the Project Status Green or Red, created for Nexus migration</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Used to have field values as Off plan, Completed and Ready.</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Off Plan</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Size_Type__c.field-meta.xml
<CustomField>
    <fullName>Size_Type__c</fullName>
    <description>Size Type</description>
    <inlineHelpText>select Size Type</inlineHelpText>
    <label>Size Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Hospitality(Hotel,Motels,Resorts)</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>Bunglow</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Among Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Towers__c.field-meta.xml
<CustomField>
    <fullName>Total_Towers__c</fullName>
    <description>This field fetches the total number of towers per project</description>
    <label>Total Towers</label>
    <summaryFilterItems>
        <field>Module__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Tower</value>
    </summaryFilterItems>
    <summaryForeignKey>Module__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <description>This field provides us the total number of apartments/flats per project</description>
    <label>Total Units</label>
    <summaryFilterItems>
        <field>Module__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Unit</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Module__c.Unit_Status__c</field>
        <operation>notEqual</operation>
        <value>Refuge</value>
    </summaryFilterItems>
    <summaryForeignKey>Module__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/Reim_FilterListLogic.cls
public class Reim_FilterListLogic {
    @AuraEnabled(cacheable=true)
    public static List<Project__c> filterLogic(String projectType,String projectStatus, String location) {
        List<Project__c> projectList4 = new List<Project__c>();
        if(location=='All'){
            String locQuery = 'SELECT Id, Name, Project_Header__c,Project_Location__c, Project_Status__c, Project_Type__c, Size_Type__c,Project_Address__City__s,Total_Towers__c,Total_Units__c  FROM Project__c ';
            if(projectType=='All'){
                if(projectStatus=='All'){
                    system.debug(locQuery);
                    projectList4 = Database.query(locQuery);
                }
                else if(projectStatus!='All'){
                        locQuery=locQuery+' where project_status__c=:projectStatus ';
                        system.debug(locQuery);
                        projectList4 = Database.query(locQuery);
                }
            }
            else if(projectType!='All'){
                    if(projectStatus=='All'){
                    locQuery=locQuery+' where project_type__c=:projectType ';
                    system.debug(locQuery);
                    projectList4 = Database.query(locQuery);
                }
                else if(projectStatus!='All'){
                        locQuery=locQuery+' where project_status__c=:projectStatus and project_type__c=:projectType';
                        system.debug(locQuery);
                        projectList4 = Database.query(locQuery);
                }
            }
        }
        else if(location!='All'){
            String locQuery = 'SELECT Id, Name, Project_Header__c,Project_Location__c, Project_Status__c, Project_Type__c, Size_Type__c,Project_Address__City__s  FROM Project__c where Project_Address__City__s=:location ';
            if(projectType=='All'){
                if(projectStatus=='All'){
                    system.debug(locQuery);
                    projectList4 = Database.query(locQuery);
                }
                else if(projectStatus!='All'){
                        locQuery=locQuery+' AND project_status__c=:projectStatus ';
                        system.debug(locQuery);
                        projectList4 = Database.query(locQuery);
                }
            }
            else if(projectType!='All'){
                    if(projectStatus=='All'){
                    locQuery=locQuery+' AND project_type__c=:projectType ';
                    system.debug(locQuery);
                    projectList4 = Database.query(locQuery);
                }
                else if(projectStatus!='All'){
                        locQuery=locQuery+' AND project_status__c=:projectStatus and project_type__c=:projectType';
                        system.debug(locQuery);
                        projectList4 = Database.query(locQuery);
                }
            }
        }
        system.debug(projectList4.size());
    system.debug(projectList4);
    return projectList4;
    }
}