force-app/main/default/objects/Payment_Plan_Detail__c/fields/Installment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Installment_Amount__c</fullName>
    <label>Installment Amount (AED)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Installment_No__c.field-meta.xml
<CustomField>
    <fullName>Installment_No__c</fullName>
    <label>Installment No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN01</fullName>
                <label>in01</label>
            </value>
            <value>
                <fullName>IN02</fullName>
                <label>in02</label>
            </value>
            <value>
                <fullName>in03</fullName>
            </value>
            <value>
                <fullName>in04</fullName>
            </value>
            <value>
                <fullName>in05</fullName>
            </value>
            <value>
                <fullName>in06</fullName>
            </value>
            <value>
                <fullName>in07</fullName>
            </value>
            <value>
                <fullName>in08</fullName>
            </value>
            <value>
                <fullName>in09</fullName>
            </value>
            <value>
                <fullName>in10</fullName>
            </value>
            <value>
                <fullName>in11</fullName>
            </value>
            <value>
                <fullName>in12</fullName>
            </value>
            <value>
                <fullName>in13</fullName>
            </value>
            <value>
                <fullName>in14</fullName>
            </value>
            <value>
                <fullName>in15</fullName>
            </value>
            <value>
                <fullName>in16</fullName>
            </value>
            <value>
                <fullName>in17</fullName>
            </value>
            <value>
                <fullName>in18</fullName>
            </value>
            <value>
                <fullName>in19</fullName>
            </value>
            <value>
                <fullName>in20</fullName>
            </value>
            <value>
                <fullName>in21</fullName>
            </value>
            <value>
                <fullName>in22</fullName>
            </value>
            <value>
                <fullName>in23</fullName>
            </value>
            <value>
                <fullName>in24</fullName>
            </value>
            <value>
                <fullName>in25</fullName>
            </value>
            <value>
                <fullName>in26</fullName>
            </value>
            <value>
                <fullName>in27</fullName>
            </value>
            <value>
                <fullName>in28</fullName>
            </value>
            <value>
                <fullName>in29</fullName>
            </value>
            <value>
                <fullName>in30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resale Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Plan_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Payment_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan Detail</label>
    <referenceTo>Payment_Plan_Detail__c</referenceTo>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Progressed</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>UnPaid</fullName>
                <isActive>false</isActive>
                <label>UnPaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PPDReminderBatch.cls
//Keep Batch Size as1
public class PPDReminderBatch implements Database.Batchable<sObject>{

    public static String emailBodyTemplate = 'Dear {1},\n\n'+
                                             'I hope you\'re well. This is a friendly reminder that the payment of AED {2} for invoice #{3} is due on {4}. Please let us know if you\'ve already made the payment or if you need any assistance.\n\n'+
                                             'Thank you for your attention to this matter!';
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        Date dueDate =  Date.valueOf(Label.PPD_Email_Due_Date);
        String query = 'SELECT Id, Name, Opportunity__c, Opportunity__r.AccountId, Opportunity__r.Account.Name, Opportunity__r.Account.PersonEmail, Status__c, Invoice_Due_Date__c,Installment_No__c, Installment_Amount__c FROM Payment_Plan_Detail__c';
        query += ' WHERE Status__c NOT IN (\'Paid\') AND Opportunity__r.AccountId != NULL AND Invoice_Due_Date__c =: dueDate';
        System.debug('>> '+ query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Payment_Plan_Detail__c> scope){
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        Payment_Plan_Detail__c objPPD = scope[0];
        if(objPPD.Opportunity__r.Account.PersonEmail != null){
            // Create Email
            String subject = 'Payment reminder for Invoice# ' + objPPD.Installment_No__c;
            String emailBody = emailBodyTemplate.replace('{1}', objPPD.Opportunity__r.Account.Name);
            emailBody = emailBody.replace('{2}', String.valueOf(objPPD.Installment_Amount__c));   
            emailBody = emailBody.replace('{3}', objPPD.Installment_No__c);
            emailBody = emailBody.replace('{4}', String.valueOf(objPPD.Invoice_Due_Date__c));

            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setToAddresses( new List<String>{objPPD.Opportunity__r.Account.PersonEmail} );
            message.setSubject(subject);
            message.setplaintextbody(emailBody);
            emailList.add(message);

            if(!emailList.isEmpty()){
                Messaging.SendEmailResult[] emailResults = Messaging.sendEmail(emailList); //Sending email
                for(Messaging.SendEmailResult emailResult : emailResults){
                    if(emailResult.IsSuccess()){
                        Task emailActivityTask = new Task();
                        emailActivityTask.Subject = subject;
                        emailActivityTask.Description = emailBody;
                        emailActivityTask.WhatId = objPPD.Opportunity__r.AccountId;
                        emailActivityTask.Priority = 'Normal';
                        emailActivityTask.Status = 'Closed';
                        emailActivityTask.TaskSubtype = 'Email';
                        emailActivityTask.ActivityDate = Date.today();
                        insert emailActivityTask;       //Creating EMail Activity
                    }
                }
            }
        }
    }

    public void finish(Database.BatchableContext BC){}
}