force-app/main/default/objects/AR_Applied_For__c/fields/Applied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Amount__c</fullName>
    <label>Applied Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>AR_Invoice__c</referenceTo>
    <relationshipName>Applied_For</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <label>Receipt</label>
    <referenceTo>AR_Receipt__c</referenceTo>
    <relationshipName>Applied_For</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>The field is used to store the source of records that have been migrated.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Unapplied</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <isActive>false</isActive>
                <label>Reversed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AR_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Amount_In_Words__c.field-meta.xml
<CustomField>
    <fullName>Amount_In_Words__c</fullName>
    <label>Amount In Words</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/issued_To__c.field-meta.xml
<CustomField>
    <fullName>issued_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>issued To</label>
    <referenceTo>AR_Legal_Entity__c</referenceTo>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Omit_fifo__c.field-meta.xml
<CustomField>
    <fullName>Omit_fifo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Omit fifo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Oracle_Migrated__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oracle Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>This field stores the Source of the records</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <displayFormat>C-{000000}</displayFormat>
    <label>Transaction Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Trigger_Amount__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Amount__c</fullName>
    <description>Backend use</description>
    <label>Trigger Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/AR_Receipt__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Amount_In_Words__c.field-meta.xml
<CustomField>
    <fullName>Amount_In_Words__c</fullName>
    <label>Amount In Words</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Applied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Amount__c</fullName>
    <label>Applied Amount</label>
    <summarizedField>AR_Applied_For__c.Applied_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>AR_Applied_For__c.Status__c</field>
        <operation>equals</operation>
        <value>Applied</value>
    </summaryFilterItems>
    <summaryForeignKey>AR_Applied_For__c.Receipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Charge_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Is_Dummy_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Is_Dummy_Receipt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dummy Receipt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Issued_To__c.field-meta.xml
<CustomField>
    <fullName>Issued_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issued To</label>
    <referenceTo>AR_Legal_Entity__c</referenceTo>
    <relationshipName>Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Omit_fifo__c.field-meta.xml
<CustomField>
    <fullName>Omit_fifo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Omit fifo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Oracle_Migrated__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oracle Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Real Connect Payments</fullName>
            </value>
            <value>
                <fullName>Payment Links</fullName>
            </value>
            <value>
                <fullName>Direct Cash Deposit</fullName>
            </value>
            <value>
                <fullName>Direct Cheque Deposit</fullName>
            </value>
            <value>
                <fullName>Manager Cheque</fullName>
            </value>
            <value>
                <fullName>NOS Services</fullName>
            </value>
            <value>
                <fullName>PDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Date__c</fullName>
    <label>Receipt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Applied</fullName>
            </value>
            <value>
                <fullName>Partially Applied</fullName>
            </value>
            <value>
                <fullName>Not applied/Hold</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <displayFormat>R-{000000}</displayFormat>
    <label>Transaction Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Trigger_Amount__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Amount__c</fullName>
    <description>Backend use</description>
    <label>Trigger Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Test</fullName>
    </customValue>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AR_ReceiptHelper.cls
public class AR_ReceiptHelper {
    public static void fillTriggerAmount(List<AR_Receipt__c> newList) 
    {
        for(AR_Receipt__c rec: newList)
        {
            rec.Trigger_Amount__c = rec.Amount__c;
            if(String.ValueOf(rec.Receipt_Date__c) == '' || String.ValueOf(rec.Receipt_Date__c) == null)
            {
                rec.Receipt_Date__c = System.Today();   
            }
            //rec.Amount_In_Words__c = AR_NumberToWords.convertNumberToWords(Integer.ValueOf(rec.Amount__c));
            //rec.Amount_In_Words__c = AR_NumberToWords.convertNumberToWords(rec.Amount__c);// Added as part of Bug Fix SAR-492
        }
    }
    
    public static void ApplyReceiptsFIFO(List<AR_Receipt__c> newList) {
        List<AR_Invoice__c> genericInvoiceList = new List<AR_Invoice__c>();
        List<AR_Invoice__c> receiptOtherInvoices = new List<AR_Invoice__c>();
        List<AR_Invoice__c> invoicesToUpdate = new List<AR_Invoice__c>();
        List<AR_Receipt__c> receiptInstallmentList = new List<AR_Receipt__c>();
        List<AR_Receipt__c> receiptOtherList = new List<AR_Receipt__c>();
        List<AR_Receipt__c> receiptsToUpdate = new List<AR_Receipt__c>();
        List<AR_Applied_For__c> appliedForToInsert = new List<AR_Applied_For__c>();
        Set<Id> oppIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Set<Id> entityIds = new Set<Id>();
        
        for(AR_Receipt__c rec : newList)
        {
            if(rec.Oracle_Migrated__c == true || rec.Omit_fifo__c == true)
            {
                break;
            }
            if(String.isNotEmpty(rec.Opportunity__c)){
           	 	oppIds.add(rec.Opportunity__c);
            }
            if(String.isNotEmpty(rec.Account__c)){
           	 	accIds.add(rec.Account__c);
            }
            if(rec.Opportunity__c == null && rec.Is_Dummy_Receipt__c == false && rec.Issued_To__c != null)
            {
                entityIds.add(rec.Issued_To__c); 
            }
            receiptInstallmentList.add(rec);
        }
        List<AR_Invoice__c> installmentInvoiceList = new List<AR_Invoice__c>();
        List<AR_Invoice__c> entityInvoiceList = new List<AR_Invoice__c>();
        List<AR_Invoice__c> accountInvoiceList = new List<AR_Invoice__c>();
        
        if (Schema.sObjectType.AR_Invoice__c.isAccessible())
        {
            installmentInvoiceList = [SELECT Id, Transaction_Id__c,Opportunity__c,Status__c,Trigger_Amount__c, Amount__c, Invoice_Date__c, Charge_Type__c 
                                      FROM AR_Invoice__c 
                                      WHERE Opportunity__c IN:oppIds AND Opportunity__c != null AND Status__c != 'Fully Paid' AND Status__c != 'Reversed'
                                      ORDER BY Invoice_Date__c ASC];
            
            if(entityIds.size() > 0)
            {
                entityInvoiceList = [SELECT Id, Transaction_Id__c,Opportunity__c,Status__c,Trigger_Amount__c, Amount__c, Invoice_Date__c, Charge_Type__c,Account__c,issued_To__c 
                                     FROM AR_Invoice__c 
                                     WHERE Opportunity__c = null AND Account__c = null AND issued_To__c IN:entityIds AND Status__c != 'Fully Paid' AND Status__c != 'Reversed'
                                     ORDER BY Invoice_Date__c ASC];
                
            }
            
            
            if(accIds.size()>0)
            {
                accountInvoiceList = [SELECT Id,Transaction_Id__c, Opportunity__c,Status__c,Trigger_Amount__c, Amount__c, Invoice_Date__c, Charge_Type__c,Account__c,issued_To__c 
                                      FROM AR_Invoice__c 
                                      WHERE Opportunity__c = null AND Account__c IN:accIds AND Account__c !=null AND Status__c != 'Fully Paid' AND Status__c != 'Reversed'
                                      ORDER BY Invoice_Date__c ASC];
                
            }
            
        }
        
        
        Map<Id,List<AR_Invoice__c>> invInsMap = new Map<Id,List<AR_Invoice__c>>();
        for(AR_Invoice__c inv : installmentInvoiceList)
        {
            if(!invInsMap.containsKey(inv.Opportunity__c))
            {
                invInsMap.put(inv.Opportunity__c, new List<AR_Invoice__c>());
                invInsMap.get(inv.Opportunity__c).add(inv);
            } else 
            {
                invInsMap.get(inv.Opportunity__c).add(inv);
            }
        }
        
        Map<Id,List<AR_Invoice__c>> invEntityMap = new Map<Id,List<AR_Invoice__c>>();
        for(AR_Invoice__c inv : entityInvoiceList)
        {
            if(!invEntityMap.containsKey(inv.issued_To__c))
            {
                invEntityMap.put(inv.issued_To__c, new List<AR_Invoice__c>());
                invEntityMap.get(inv.issued_To__c).add(inv);
            } else 
            {
                invEntityMap.get(inv.issued_To__c).add(inv);
            }
        }
        
        Map<Id,List<AR_Invoice__c>> invAccountMap = new Map<Id,List<AR_Invoice__c>>();
        for(AR_Invoice__c inv : accountInvoiceList)
        {
            if(!invAccountMap.containsKey(inv.Account__c))
            {
                invAccountMap.put(inv.Account__c, new List<AR_Invoice__c>());
                invAccountMap.get(inv.Account__c).add(inv);
            } else 
            {
                invAccountMap.get(inv.Account__c).add(inv);
            }
        }
        
        //Applying Installment Receipt on Insallment Invoices
        for(AR_Receipt__c rec : receiptInstallmentList)
        {
            AR_Receipt__c tmp = new AR_Receipt__c();
            tmp.Id = rec.Id;
            tmp.Trigger_Amount__c = rec.Trigger_Amount__c;
            genericInvoiceList = invInsMap.get(rec.Opportunity__c);
            if(genericInvoiceList == null)
            {
                genericInvoiceList = invEntityMap.get(rec.Issued_To__c);
            }
            if(genericInvoiceList == null)
            {
                genericInvoiceList = invAccountMap.get(rec.Account__c);
            }
            if(genericInvoiceList != null)
            {
                Double currReceiptAmount = rec.Trigger_Amount__c;                
                for(AR_Invoice__c inv : genericInvoiceList)
                {
                    String swithType = 'NormalFiFo';
                    if((rec.Payment_Type__c == 'Real Connect Payments' || rec.Source_System__C == 'Kiosk') &&  rec.Charge_Type__c !='Installments' && rec.Charge_Type__c !='CC Charges'){
                        swithType = 'RealConnectFIFO';
                    }
                    switch on swithType {
                        when 'RealConnectFIFO' {
                            // Adding below Logic as the Trigger
                            if(currReceiptAmount > 0 && rec.External_ID__c  == inv.Transaction_Id__c &&   rec.Charge_Type__c == inv.Charge_Type__c)
                            {
                                AR_Applied_For__c appFor = new AR_Applied_For__c();
                                appFor = createAppliedForRecord(currReceiptAmount,inv.Id,rec.Id,'Applied');
                                if(appFor.Applied_Amount__c > 0)
                                {
                                    appliedForToInsert.add(appFor);
                                }
                                inv.Status__c = 'Fully Paid'; // Invoice Details
                                inv.Trigger_Amount__c = 0;    // Invoice Details
                                tmp.Status__c = 'Fully Applied'; // Receipt Details
                                tmp.Trigger_Amount__c = 0;  // Receipt Details
                                if(!receiptsToUpdate.Contains(tmp))
                                {
                                    receiptsToUpdate.add(tmp);
                                }
                                if(!invoicesToUpdate.Contains(inv))
                                {
                                    invoicesToUpdate.add(inv);
                                }
                                currReceiptAmount = 0;
                            }
                        }
                        when else {
                            if(inv.Trigger_Amount__c == currReceiptAmount && currReceiptAmount > 0 && rec.Charge_Type__c == inv.Charge_Type__c)
                            {
                                AR_Applied_For__c appFor = new AR_Applied_For__c();
                                appFor = createAppliedForRecord(currReceiptAmount,inv.Id,rec.Id,'Applied');
                                if(appFor.Applied_Amount__c > 0)
                                {
                                    appliedForToInsert.add(appFor);
                                }
                                inv.Status__c = 'Fully Paid'; // Invoice Details
                                inv.Trigger_Amount__c = 0;    // Invoice Details
                                tmp.Status__c = 'Fully Applied'; // Receipt Details
                                tmp.Trigger_Amount__c = 0;  // Receipt Details
                                if(!receiptsToUpdate.Contains(tmp))
                                {
                                    receiptsToUpdate.add(tmp);
                                }
                                if(!invoicesToUpdate.Contains(inv))
                                {
                                    invoicesToUpdate.add(inv);
                                }
                                currReceiptAmount = 0;
                            }
                            if(currReceiptAmount > 0 && inv.Trigger_Amount__c < currReceiptAmount && inv.Trigger_Amount__c > 0 && rec.Charge_Type__c == inv.Charge_Type__c)
                            {
                                AR_Applied_For__c appFor = new AR_Applied_For__c();
                                appFor = createAppliedForRecord((Double)inv.Trigger_Amount__c,inv.Id,rec.Id,'Applied');
                                tmp.Trigger_Amount__c -= inv.Trigger_Amount__c; // Receipt Details
                                tmp.Status__c = 'Partially Applied';    // Receipt Details
                                currReceiptAmount -= inv.Trigger_Amount__c; // Invoice Details
                                inv.Trigger_Amount__c = 0;  // Invoice Details
                                inv.Status__c = 'Fully Paid'; // Invoice Details
                                if(!receiptsToUpdate.Contains(tmp))
                                {
                                    receiptsToUpdate.add(tmp);
                                }
                                if(!invoicesToUpdate.Contains(inv))
                                {
                                    invoicesToUpdate.add(inv);
                                }
                                if(appFor.Applied_Amount__c > 0)
                                {
                                    appliedForToInsert.add(appFor);
                                }
                            }
                            if(currReceiptAmount > 0 && inv.Trigger_Amount__c > currReceiptAmount && rec.Charge_Type__c == inv.Charge_Type__c)
                            {
                                AR_Applied_For__c appFor = new AR_Applied_For__c();
                                appFor = createAppliedForRecord(currReceiptAmount,inv.Id,rec.Id,'Applied');
                                inv.Trigger_Amount__c -= currReceiptAmount;  // Invoice Details
                                inv.Status__c = 'Partially Paid';            // Invoice Details
                                currReceiptAmount = 0;  // Receipt Details
                                tmp.Trigger_Amount__c -= inv.Trigger_Amount__c;  // Receipt Details
                                tmp.Status__c = 'Fully Applied'; // Receipt Details
                                if(!receiptsToUpdate.Contains(tmp))
                                {
                                    receiptsToUpdate.add(tmp);
                                }
                                if(!invoicesToUpdate.Contains(inv))
                                {
                                    invoicesToUpdate.add(inv);
                                }
                                if(appFor.Applied_Amount__c > 0)
                                {
                                    appliedForToInsert.add(appFor);
                                }
                            }   
                        }
                    }
                }
            }else
            {
                tmp.Status__c = 'Not applied/Hold';
                if(!receiptsToUpdate.Contains(tmp))
                {
                    receiptsToUpdate.add(tmp);
                }
            }
            
            if(genericInvoiceList == null)
            {
                tmp.Status__c = 'Not applied/Hold';
                if(!receiptsToUpdate.Contains(tmp))
                {
                    receiptsToUpdate.add(tmp);
                }
            }
        }
        
        if(!Test.isRunningTest()){
            if(appliedForToInsert.Size() > 0)
            {
                insert appliedForToInsert;
            }
        }
        if(invoicesToUpdate.Size() > 0)
        {
            update invoicesToUpdate;
        }
        
        if(receiptsToUpdate.Size() > 0)
        {
            update receiptsToUpdate;
        }
        
        
    }
    
    public static AR_Applied_For__c createAppliedForRecord(Double amountToBeApplied,Id invId,Id recId,String appliedForStatus){
        AR_Applied_For__c appFor = new AR_Applied_For__c();
        appFor.Applied_Amount__c = amountToBeApplied;
        appFor.Invoice__c = invId;
        appFor.Receipt__c = recId;
        appFor.Status__c = appliedForStatus;
        return appFor;
    }

}