force-app/main/default/objects/AR_Applied_For__c/fields/Applied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Amount__c</fullName>
    <label>Applied Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Charge_Code__c.field-meta.xml
<CustomField>
    <fullName>Charge_Code__c</fullName>
    <formula>Invoice__r.Charge_Code_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Charge Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>AR_Invoice__c</referenceTo>
    <relationshipName>Applied_For</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <label>Receipt</label>
    <referenceTo>AR_Receipt__c</referenceTo>
    <relationshipName>Applied_For</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AR_Applied_For__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Unapplied</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
                <isActive>false</isActive>
                <label>Reversed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AR_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Charge_Code__c.field-meta.xml
<CustomField>
    <fullName>Charge_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge Code</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>AR_Charge_Code__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.CreatedDate</field>
            <operation>lessThan</operation>
            <value>5/20/2025, 12:00 AM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AR_Charge_Code__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/issued_To__c.field-meta.xml
<CustomField>
    <fullName>issued_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>issued To</label>
    <referenceTo>AR_Legal_Entity__c</referenceTo>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Omit_fifo__c.field-meta.xml
<CustomField>
    <fullName>Omit_fifo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Omit fifo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Oracle_Migrated__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oracle Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Fully Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Invoice__c/fields/Trigger_Amount__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Amount__c</fullName>
    <description>Backend use</description>
    <label>Trigger Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Applied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Amount__c</fullName>
    <label>Applied Amount</label>
    <summarizedField>AR_Applied_For__c.Applied_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>AR_Applied_For__c.Status__c</field>
        <operation>equals</operation>
        <value>Applied</value>
    </summaryFilterItems>
    <summaryForeignKey>AR_Applied_For__c.Receipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Charge_Code__c.field-meta.xml
<CustomField>
    <fullName>Charge_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charge Code</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>AR_Charge_Code__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.CreatedDate</field>
            <operation>lessThan</operation>
            <value>5/20/2025, 12:00 AM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AR_Charge_Code__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Charge_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Financial_Status__c.field-meta.xml
<CustomField>
    <fullName>Financial_Status__c</fullName>
    <label>Financial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UnReconciled</fullName>
                <default>true</default>
                <label>UnReconciled</label>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Issued_To__c.field-meta.xml
<CustomField>
    <fullName>Issued_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issued To</label>
    <referenceTo>AR_Legal_Entity__c</referenceTo>
    <relationshipName>Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issued From</label>
    <referenceTo>AR_Legal_Entity__c</referenceTo>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Omit_fifo__c.field-meta.xml
<CustomField>
    <fullName>Omit_fifo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Omit fifo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Oracle_Migrated__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Migrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Oracle Migrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Reservation_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Receipt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reservation Receipt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Applied</fullName>
            </value>
            <value>
                <fullName>Partially Applied</fullName>
            </value>
            <value>
                <fullName>Not applied/Hold</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Trigger_Amount__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Amount__c</fullName>
    <description>Backend use</description>
    <label>Trigger Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AR_Receipt__c/fields/Unapplied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unapplied_Amount__c</fullName>
    <formula>Amount__c -  Applied_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unapplied Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AR_InvoiceHelper.cls
public class AR_InvoiceHelper {
    public static void fillTriggerAmount(List<AR_Invoice__c> newList) 
    {
        for(AR_Invoice__c inv: newList)
        {
            inv.Trigger_Amount__c = inv.Amount__c;
            if(String.ValueOf(inv.Invoice_Date__c) == '' || String.ValueOf(inv.Invoice_Date__c) == null)
            {
                inv.Invoice_Date__c = System.Today();
            }

        } 
    }
    
    public static void ApplyInvoicesFIFO(List<AR_Invoice__c> newList) 
    {
        List<AR_Receipt__c> genericReceiptList = new List<AR_Receipt__c>();
        List<AR_Receipt__c> receiptOtherInvoices = new List<AR_Receipt__c>();
        List<AR_Receipt__c> receiptsToUpdate = new List<AR_Receipt__c>();
        List<AR_Invoice__c> invoiceInstallmentList = new List<AR_Invoice__c>();
        List<AR_Invoice__c> invoiceOtherList = new List<AR_Invoice__c>();
        List<AR_Invoice__c> invoicesToUpdate = new List<AR_Invoice__c>();
        List<AR_Applied_For__c> appliedForToInsert = new List<AR_Applied_For__c>();
        Set<Id> oppIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Set<Id> entityIds = new Set<Id>();
        
        for(AR_Invoice__c inv : newList)
        {
            if(inv.Oracle_Migrated__c == true || inv.Omit_fifo__c == true){
                break;
            }
           if(String.isNotEmpty(inv.Opportunity__c)){
            	oppIds.add(inv.Opportunity__c);
            }
            if(String.isNotEmpty(inv.Account__c)){
               accIds.add(inv.Account__c); 
            }
            if(inv.Opportunity__c == null && inv.issued_To__c !=null)
            {
                entityIds.add(inv.issued_To__c);
            }
            invoiceInstallmentList.add(inv);
        }
        List<AR_Receipt__c> installmentReceiptList = new List<AR_Receipt__c>();
        List<AR_Receipt__c> entityReceiptList = new List<AR_Receipt__c>();
        List<AR_Receipt__c> accountReceiptList = new List<AR_Receipt__c>();
        
        if (Schema.sObjectType.AR_Receipt__c.isAccessible())
        {
            installmentReceiptList = [SELECT Id, Opportunity__c,Status__c,Trigger_Amount__c, Amount__c,Unapplied_Amount__c, Payment_Date__c, Charge_Type__c, Charge_Code__c,Reservation_Receipt__c, Financial_Status__c 
                                      FROM AR_Receipt__c 
                                      WHERE Opportunity__c IN:oppIds AND Opportunity__c != null AND Status__c != 'Fully Applied' AND Status__c != 'Cancelled' AND Financial_Status__c != 'Reversed'  
                                      ORDER BY Payment_Date__c ASC];
            if(entityIds.size() > 0)
            {
                 entityReceiptList = [SELECT Id, Opportunity__c,Status__c,Trigger_Amount__c, Amount__c,Unapplied_Amount__c, Payment_Date__c, Charge_Type__c, Charge_Code__c,Reservation_Receipt__c,Legal_Entity__c,Account__c,Financial_Status__c 
                                 FROM AR_Receipt__c 
                                 WHERE Opportunity__c = null AND Account__c = null AND Issued_To__c IN:entityIds AND Status__c != 'Fully Applied' AND Status__c != 'Cancelled' AND Financial_Status__c != 'Reversed' 
                                 ORDER BY Payment_Date__c ASC];
            }
         
            if(accIds.size()>0)
            {
                accountReceiptList = [SELECT Id, Opportunity__c,Status__c,Trigger_Amount__c, Amount__c,Unapplied_Amount__c, Payment_Date__c, Charge_Type__c, Charge_Code__c,Reservation_Receipt__c,Legal_Entity__c,Account__c,Financial_Status__c 
                                  FROM AR_Receipt__c 
                                  WHERE Opportunity__c = null AND Account__c IN:accIds AND Account__c !=null AND Status__c != 'Fully Applied' AND Status__c != 'Cancelled' AND Financial_Status__c != 'Reversed' 
                                  ORDER BY Payment_Date__c ASC];
            }
           
        }
        
        Map<Id,List<AR_Receipt__c>> receiptInsMap = new Map<Id,List<AR_Receipt__c>>();
        for(AR_Receipt__c rec : installmentReceiptList)
        {
            if(!receiptInsMap.containsKey(rec.Opportunity__c))
            {
                receiptInsMap.put(rec.Opportunity__c, new List<AR_Receipt__c>());
                receiptInsMap.get(rec.Opportunity__c).add(rec);
            } else 
            {
                receiptInsMap.get(rec.Opportunity__c).add(rec);
            }
        }
        
        Map<Id,List<AR_Receipt__c>> receiptEntityMap = new Map<Id,List<AR_Receipt__c>>();
        for(AR_Receipt__c rec : entityReceiptList)
        {
            if(!receiptEntityMap.containsKey(rec.Legal_Entity__c))
            {
                receiptEntityMap.put(rec.Legal_Entity__c, new List<AR_Receipt__c>());
                receiptEntityMap.get(rec.Legal_Entity__c).add(rec);
            } else 
            {
                receiptEntityMap.get(rec.Legal_Entity__c).add(rec);
            }
        }
        
        Map<Id,List<AR_Receipt__c>> receiptAccountMap = new Map<Id,List<AR_Receipt__c>>();
        for(AR_Receipt__c rec : accountReceiptList)
        {
            if(!receiptAccountMap.containsKey(rec.Account__c))
            {
                receiptAccountMap.put(rec.Account__c, new List<AR_Receipt__c>());
                receiptAccountMap.get(rec.Account__c).add(rec);
            } else 
            {
                receiptAccountMap.get(rec.Account__c).add(rec);
            }
        }
        
        for(AR_Invoice__c inv : invoiceInstallmentList)
        {
            AR_Invoice__c tmp = new AR_Invoice__c();
            tmp.Id = inv.Id;
            tmp.Trigger_Amount__c = inv.Trigger_Amount__c;
            genericReceiptList = receiptInsMap.get(inv.Opportunity__c);
            if(genericReceiptList == null)
            {
                genericReceiptList = receiptEntityMap.get(inv.issued_To__c);
            }
            if(genericReceiptList == null)
            {
                genericReceiptList = receiptAccountMap.get(inv.Account__c);
            }
            if(genericReceiptList != null)
            {
                Integer c = 0;
                Double currInvoiceAmount = tmp.Trigger_Amount__c;
                for(AR_Receipt__c rec : genericReceiptList)
                {
                    if(rec.Reservation_Receipt__c == true)
                    {
                        if(rec.Charge_Code__c == inv.Charge_Code__c)
                        {
                            AR_Applied_For__c appFor = new AR_Applied_For__c();
                            appFor.Applied_Amount__c = rec.Trigger_Amount__c;
                            appFor.Status__c = 'Applied';
                            appFor.Invoice__c = inv.Id;
                            appFor.Receipt__c = rec.Id;
                            tmp.Status__c = 'Fully Paid'; 
                            rec.Status__c = 'Fully Applied';
                            rec.Trigger_Amount__c = 0;
                            tmp.Trigger_Amount__c = 0;
                            currInvoiceAmount = 0; 
                            if(appFor.Applied_Amount__c > 0)
                            {
                                appliedForToInsert.add(appFor);
                            }
                            if(!receiptsToUpdate.Contains(rec))
                            {
                                receiptsToUpdate.add(rec);
                            }
                            if(!invoicesToUpdate.Contains(tmp))
                            {
                                invoicesToUpdate.add(tmp);
                            }
                        }
                    }else if (rec.Reservation_Receipt__c == false)
                    {
                        if(rec.Trigger_Amount__c == currInvoiceAmount && currInvoiceAmount > 0 && rec.Charge_Type__c == inv.Charge_Type__c)
                        {
                            AR_Applied_For__c appFor = new AR_Applied_For__c();
                            appFor.Applied_Amount__c = rec.Trigger_Amount__c;
                            appFor.Invoice__c = inv.Id;
                            appFor.Receipt__c = rec.Id;
                            appFor.Status__c = 'Applied';
                            if(appFor.Applied_Amount__c > 0)
                            {
                                appliedForToInsert.add(appFor);
                            }
                            tmp.Status__c = 'Fully Paid';
                            rec.Status__c = 'Fully Applied';
                            rec.Trigger_Amount__c = 0;
                            tmp.Trigger_Amount__c = 0;
                            if(!receiptsToUpdate.Contains(rec))
                            {
                                receiptsToUpdate.add(rec);
                            }
                            if(!invoicesToUpdate.Contains(tmp))
                            {
                                invoicesToUpdate.add(tmp);
                            }
                            currInvoiceAmount = 0;
                        }
                        if(rec.Trigger_Amount__c > 0 && rec.Trigger_Amount__c > currInvoiceAmount && currInvoiceAmount > 0 && rec.Charge_Type__c == inv.Charge_Type__c)
                        {
                            AR_Applied_For__c appFor = new AR_Applied_For__c();
                            appFor.Applied_Amount__c = currInvoiceAmount;
                            appFor.Invoice__c = inv.Id;
                            appFor.Receipt__c = rec.Id;
                            appFor.Status__c = 'Applied';
                            tmp.Status__c = 'Fully Paid';
                            rec.Status__c = 'Partially Applied';
                            rec.Trigger_Amount__c -= currInvoiceAmount;
                            currInvoiceAmount = 0;
                            tmp.Trigger_Amount__c -= rec.Trigger_Amount__c;
                            if(!receiptsToUpdate.Contains(rec))
                            {
                                receiptsToUpdate.add(rec);
                            }
                            if(!invoicesToUpdate.Contains(tmp))
                            {
                                invoicesToUpdate.add(tmp);
                            }
                            if(appFor.Applied_Amount__c > 0)
                            {
                                appliedForToInsert.add(appFor);
                            }
                            
                        }
                        
                        if(rec.Trigger_Amount__c > 0 && rec.Trigger_Amount__c < currInvoiceAmount && currInvoiceAmount > 0 && rec.Charge_Type__c == inv.Charge_Type__c)
                        {
                            AR_Applied_For__c appFor = new AR_Applied_For__c();
                            appFor.Applied_Amount__c = rec.Trigger_Amount__c;
                            appFor.Invoice__c = inv.Id;
                            appFor.Receipt__c = rec.Id;
                            appFor.Status__c = 'Applied';
                            tmp.Status__c = 'Partially Paid';
                            rec.Status__c = 'Fully Applied';
                            currInvoiceAmount -= rec.Trigger_Amount__c;
                            tmp.Trigger_Amount__c -= rec.Trigger_Amount__c;
                            rec.Trigger_Amount__c = 0;
                            if(!receiptsToUpdate.Contains(rec))
                            {
                                receiptsToUpdate.add(rec);
                            }
                            if(!invoicesToUpdate.Contains(tmp))
                            {
                                invoicesToUpdate.add(tmp);
                            }
                            if(appFor.Applied_Amount__c > 0)
                            {
                                appliedForToInsert.add(appFor);
                            }
                        }
                        c++;
                    }  
                }
            }else
            {
                tmp.Status__c = 'Pending Payment';
                if(!invoicesToUpdate.Contains(tmp))
                {
                    invoicesToUpdate.add(tmp);
                }
            }
            
            if(genericReceiptList == null)
            {
                tmp.Status__c = 'Pending Payment';
                if(!invoicesToUpdate.Contains(tmp))
                {
                    invoicesToUpdate.add(tmp);
                }   
            }
        }
                
        if(appliedForToInsert.Size() > 0)
        {
            insert appliedForToInsert;
        }
        
        if(invoicesToUpdate.Size() > 0)
        {
            update invoicesToUpdate;
        }
        
        if(receiptsToUpdate.Size() > 0)
        {
            update receiptsToUpdate;
        }
        
    }

}