force-app/main/default/objects/Due_Diligence__c/Due_Diligence__c.object-meta.xml
<CustomObject>
    <description>This object contains due diligence details of primary buyer and JO</description>
    <label>Due Diligence</label>
    <nameField>
        <displayFormat>DD - {0000}</displayFormat>
        <label>Due Diligence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Due_Diligence__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Due Diligences</relationshipLabel>
    <relationshipName>Due_Diligences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Due_Diligence__c/fields/IsPrimaryAccount__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify that it is primary Account</description>
    <label>IsPrimaryAccount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Due_Diligence__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Due Diligences</relationshipLabel>
    <relationshipName>Due_Diligences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Joint_Owner__c/Joint_Owner__c.object-meta.xml
<CustomObject>
    <label>Joint Owner</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Joint Owner No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Joint Owners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Joint_Owner__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Owners</relationshipLabel>
    <relationshipName>Joint_Owners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Joint_Owner__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Joint Owners</relationshipLabel>
    <relationshipName>Joint_Owners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DueDiligenceServiceTest.cls
@IsTest
private class DueDiligenceServiceTest {

    @IsTest
    static void createsForPrimaryContactAccountAndDistinctJointOwners() {
        Account opportunityAccount = new Account(Name = 'Opportunity Account');
        Account primaryBuyer = new Account(Name = 'Wife');
        Account jointBuyer = new Account(Name = 'Husband');
        insert new List<Account>{ opportunityAccount, primaryBuyer, jointBuyer };

        Contact primaryContact = new Contact(LastName = 'Primary Buyer', AccountId = primaryBuyer.Id);
        insert primaryContact;

        Opportunity opportunity = new Opportunity(
            Name = 'Family Purchase',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            AccountId = opportunityAccount.Id,
            Primary_Contact__c = primaryContact.Id
        );
        insert opportunity;

        insert new List<Joint_Owner__c>{
            new Joint_Owner__c(Booking__c = opportunity.Id, Account__c = jointBuyer.Id),
            new Joint_Owner__c(Booking__c = opportunity.Id, Account__c = jointBuyer.Id)
        };

        Test.startTest();
        DueDiligenceService.CreationResult firstResult =
            DueDiligenceService.createForOpportunity(opportunity.Id);
        DueDiligenceService.CreationResult secondResult =
            DueDiligenceService.createForOpportunity(opportunity.Id);
        Test.stopTest();

        System.assertEquals(2, firstResult.buyerCount);
        System.assertEquals(2, firstResult.createdCount);
        System.assertEquals(0, firstResult.existingCount);
        System.assertEquals(true, firstResult.hasJointBuyers);
        System.assertEquals(2, firstResult.buyers.size());
        System.assertEquals('Primary Buyer', firstResult.buyers[0].buyerType);
        System.assertEquals(primaryBuyer.Id, firstResult.buyers[0].accountId);
        System.assertEquals('Joint Buyer 1', firstResult.buyers[1].buyerType);
        System.assertEquals(jointBuyer.Id, firstResult.buyers[1].accountId);
        System.assertEquals(0, secondResult.createdCount);
        System.assertEquals(2, secondResult.existingCount);

        Map<Id, Due_Diligence__c> diligenceByAccount = new Map<Id, Due_Diligence__c>();
        for (Due_Diligence__c record : [
            SELECT Account__c, IsPrimaryAccount__c
            FROM Due_Diligence__c
            WHERE Opportunity__c = :opportunity.Id
        ]) {
            diligenceByAccount.put(record.Account__c, record);
        }

        System.assertEquals(2, diligenceByAccount.size());
        System.assertEquals(true, diligenceByAccount.get(primaryBuyer.Id).IsPrimaryAccount__c);
        System.assertEquals(false, diligenceByAccount.get(jointBuyer.Id).IsPrimaryAccount__c);
        System.assertEquals(false, diligenceByAccount.containsKey(opportunityAccount.Id));
    }

    @IsTest
    static void doesNotCreateDueDiligenceWithoutJointOwners() {
        Account primaryBuyer = new Account(Name = 'Only Buyer');
        insert primaryBuyer;

        Opportunity opportunity = new Opportunity(
            Name = 'Single Buyer Purchase',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            AccountId = primaryBuyer.Id
        );
        insert opportunity;

        Test.startTest();
        DueDiligenceService.CreationResult result =
            DueDiligenceService.createForOpportunity(opportunity.Id);
        Test.stopTest();

        System.assertEquals(0, result.buyerCount);
        System.assertEquals(0, result.createdCount);
        System.assertEquals(false, result.hasJointBuyers);
        System.assertEquals(0, result.buyers.size());
        System.assertEquals(
            0,
            [SELECT COUNT() FROM Due_Diligence__c WHERE Opportunity__c = :opportunity.Id]
        );
    }
}