force-app/main/default/objects/AR_PPD_Installment_Progression_Event__e/fields/Billed__c.field-meta.xml
<CustomField>
    <fullName>Billed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AR_PPD_Installment_Progression_Event__e/fields/PaymentPlanDetailId__c.field-meta.xml
<CustomField>
    <fullName>PaymentPlanDetailId__c</fullName>
    <label>PaymentPlanDetailId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_PPD_Installment_Progression_Event__e/fields/PhaseDate__c.field-meta.xml
<CustomField>
    <fullName>PhaseDate__c</fullName>
    <label>PhaseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Payment_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan Detail</label>
    <referenceTo>Payment_Plan_Detail__c</referenceTo>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Phase_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_Date__c</fullName>
    <label>Phase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Progressed</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>UnPaid</fullName>
                <isActive>false</isActive>
                <label>UnPaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AR_PPDProgressionTriggerHandler.cls
public with sharing class AR_PPDProgressionTriggerHandler {
    public static void updateProgressStatus(List<AR_PPD_Installment_Progression_Event__e> newList){
        List<Payment_Plan_Detail__c> recordsToUpdate = new List<Payment_Plan_Detail__c>();
        for (AR_PPD_Installment_Progression_Event__e event : newList) {
            try {
                if (event.PaymentPlanDetailId__c != null && event.Status__c == 'Progressed') {
                    Payment_Plan_Detail__c ppd = new Payment_Plan_Detail__c();
                    ppd.Id = event.PaymentPlanDetailId__c;
                    ppd.Status__c = event.Status__c;
                    ppd.Phase_Date__c = event.PhaseDate__c;
                    ppd.Billed__c = event.Billed__c;
                    recordsToUpdate.add(ppd);
                }
            } catch (Exception e) {
                //LoggerUtility.logExceptions(e);
            }
        }
        
        if (!recordsToUpdate.isEmpty()) {
            try {
                Database.SaveResult[] DBrecordsToUpdate = Database.update(recordsToUpdate,false);
            } catch (Exception e) {
                //LoggerUtility.logExceptions(e);
            }
        }
    }
}