force-app/main/default/objects/blocking__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/blocking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Blocking</relationshipLabel>
    <relationshipName>Blocking</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/blocking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Blocking</relationshipLabel>
    <relationshipName>Blocking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Backend</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit / Apartment</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Opportunities (Unit / Apartment)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tower__c.Project__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Released</fullName>
            </value>
            <value>
                <fullName>Available for Sale</fullName>
            </value>
            <value>
                <fullName>Blocked by Mgmt</fullName>
                <label>Blocked by management</label>
            </value>
            <value>
                <fullName>Blocked by Sales Head</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled Unit- AFS</fullName>
                <label>Cancellation-Available for Use</label>
            </value>
            <value>
                <fullName>Under Cancellation</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <isActive>false</isActive>
                <label>Available</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Blocked for Customer</fullName>
                <isActive>false</isActive>
                <label>Blocked for Customer</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <isActive>false</isActive>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Hold As Per HOD</fullName>
                <isActive>false</isActive>
                <label>Hold As Per HOD</label>
            </value>
            <value>
                <fullName>Hold By C P</fullName>
                <isActive>false</isActive>
                <label>Hold By C P</label>
            </value>
            <value>
                <fullName>Hold By Employee</fullName>
                <isActive>false</isActive>
                <label>Hold By Employee</label>
            </value>
            <value>
                <fullName>Hold For MOU</fullName>
                <isActive>false</isActive>
                <label>Hold For MOU</label>
            </value>
            <value>
                <fullName>Hold For Transfer</fullName>
                <isActive>false</isActive>
                <label>Hold For Transfer</label>
            </value>
            <value>
                <fullName>Management Hold</fullName>
                <isActive>false</isActive>
                <label>Management Hold</label>
            </value>
            <value>
                <fullName>Sold - C</fullName>
                <isActive>false</isActive>
                <label>Sold - C</label>
            </value>
            <value>
                <fullName>Sold - T</fullName>
                <isActive>false</isActive>
                <label>Sold - T</label>
            </value>
            <value>
                <fullName>Sold By Transfer</fullName>
                <isActive>false</isActive>
                <label>Sold By Transfer</label>
            </value>
            <value>
                <fullName>Transferred</fullName>
                <isActive>false</isActive>
                <label>Transferred</label>
            </value>
            <value>
                <fullName>Under Transfer</fullName>
                <isActive>false</isActive>
                <label>Under Transfer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BlockPageController.cls
public class BlockPageController {
    public Product2 prod{get;set;}
    public Product2 prod1{get;set;}
    public blocking__c block{get;set;}
    public string callfunc{get;set;}
    public  id prodId{get;set;}
    public string OptyID{get;set;}
    public String message{get;set;}
    public string blockMessage{get;set;}
    public boolean displayPopup {get; set;}     
    
    
    public PageReference BlockPageControllerAction(){
        blockMessage = ApexPages.currentPage().getParameters().get('block');
        if(blockMessage != NULL){
            callfunc='<script> showToast(\'' +blockMessage+ '\'); </script>';
        }
        
        prod = new Product2();
        block = new blocking__c();
        string pid = ApexPages.currentPage().getParameters().get('pid');
        OptyID = ApexPages.currentPage().getParameters().get('OptyID');
        system.debug('OptyID'+ApexPages.currentPage().getParameters().get('OptyID'));
        Opportunity Opp = new Opportunity();
        if(OptyID != null && !string.isBlank(OptyID) && OptyID!='null'){
           Opp = [Select ID, Name from Opportunity where ID =: OptyID];
            system.debug('OptyID'+Opp);
            if(Opp != NULL){
                block.Opportunity__c = Opp.Id;
            }
        }
        system.debug('pid'+pid);
        try{
            if(pid != NULL && pid != ''){
                prod1 = [select Id,Name,Project__c,Tower__c, Unit_Status__c, Opportunity__c from Product2 where Id =: pid];
                system.debug('prod1'+prod1);
                if(prod1!=NULL){
                }
            }
        }catch(exception e){
            
        }
        if(blockMessage != NULL){
            return new PageReference('/apex/S_InventoryMatrixview');
        }
        return NULL;
    }
    public void closePopup() {        
        displayPopup = false;    
    } 
    
    Public string selectedname{get;set;}
    Public List<Selectoption> getselectedaccnamefields(){
        
        Schema.DescribeFieldResult fieldResult = Product2.Unit_Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        List<Selectoption> lstnamesel = new List<selectoption>();
        lstnamesel.add(new selectOption('', '- None -'));
        for( Schema.PicklistEntry f : ple)
        {
            lstnamesel.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        return lstnamesel; 
    }
    
    public PageReference save(){
        displayPopUp = true;
        try{
            block.Unit__c = prod1.Id;
            Insert block;
            if(block.Id != NULL){ 
                if(block.Action__c == 'Block'){
                    Update new Product2(Id=prod1.Id,Unit_Status__c='Hold');
                    system.debug('inside Hold');
                    displayPopup = true;    
                    Message = 'SUCCESS : Blocking of unit '+prod1.Name+ ' against Opportunity Successfully done';
                }else{
                    Message = 'Unit '+prod1.Name+' status set Unblock';
                }
            }else{
                Message= 'Fail : Blocking of unit '+prod1.Name+ ' against Opportunity fail';
            }
        }
        catch(exception e){
            Message = 'Fail : System failure while blocking unit --> Error : '+e;    
        }
        return NULL;
    }
    
    public PageReference cancel(){
        return new PageReference('/apex/S_InventoryMatrixview?projectsent='+prod.Project__c+'&towersent='+prod.Tower__c);
    }
    
}