force-app/main/default/objects/Account/fields/City_O__c.field-meta.xml
<CustomField>
    <fullName>City_O__c</fullName>
    <label>City O</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <formula>ShippingStreet &amp; &quot;, &quot; &amp;
ShippingCity &amp; &quot;, &quot; &amp;
ShippingState &amp; &quot; - &quot; &amp;
ShippingPostalCode &amp; &quot;, &quot; &amp;
ShippingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Kerla</fullName>
            </value>
            <value>
                <fullName>Northland</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City_O__c.field-meta.xml
<CustomField>
    <fullName>City_O__c</fullName>
    <label>City (O)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Indore</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Visakhapatnam[a][5]</fullName>
            </value>
            <value>
                <fullName>Pimpri-Chinchwad</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
            <value>
                <fullName>Vadodara</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Ludhiana</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Nashik</fullName>
            </value>
            <value>
                <fullName>Faridabad</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Saleable__c.field-meta.xml
<CustomField>
    <fullName>Product_Saleable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Saleable</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tower1__c.field-meta.xml
<CustomField>
    <fullName>Tower1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Advanced_Received__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Received__c</fullName>
    <label>Advanced Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <label>Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Cheque_Clearing_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Clearing_Date__c</fullName>
    <label>Cheque Clearing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Cheque_No__c.field-meta.xml
<CustomField>
    <fullName>Cheque_No__c</fullName>
    <label>Assignment No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Clearing_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Clearing_Document_Number__c</fullName>
    <label>Clearing Document Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Customer_Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Receipt_Number__c</fullName>
    <label>Customer Receipt Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Demand_Letter_Date__c.field-meta.xml
<CustomField>
    <fullName>Demand_Letter_Date__c</fullName>
    <label>Demand Letter Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Document_Clearing_Date__c.field-meta.xml
<CustomField>
    <fullName>Document_Clearing_Date__c</fullName>
    <label>Document Clearing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <formula>Product__r.Material_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Reversal_Doc__c.field-meta.xml
<CustomField>
    <fullName>Reversal_Doc__c</fullName>
    <label>Reversal Doc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Reversal_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reversal_Reason__c</fullName>
    <label>Reversal Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Reversal_Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reversal_Reason_Code__c</fullName>
    <label>Reversal Reason Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sp_GL_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Sp_GL_Indicator__c</fullName>
    <label>Sp GL Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sp_GL_Indicator_Code__c.field-meta.xml
<CustomField>
    <fullName>Sp_GL_Indicator_Code__c</fullName>
    <label>Sp GL Indicator Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Material Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenerateReceiptController.cls
public class GenerateReceiptController {
    public List<Payment__c> pList {get;set;}
    
    public GenerateReceiptController(){
        Id payId = ApexPages.currentPage().getParameters().get('id');
        pList = new List<Payment__c>();
        
        pList = [SELECT Id, Name,Opportunity__c, Account__c,Customer_Code__c,Opportunity__r.Project__r.Name,Demand_Letter_Date__c,Due_Date__c,
                 Opportunity__r.Tower1__r.Name,Opportunity__r.Product_Saleable__r.Material_Code__c,Document_Number__c,
                 Opportunity__r.Product_Saleable__r.Name,Opportunity__r.Account.Name,Opportunity__r.Account.Customer_Address__c,
                 Opportunity__r.Account.City_O__c,Opportunity__r.Account.Pincode__c,Opportunity__r.Account.State_Province__c,
                 Opportunity__r.Account.Country__c,Opportunity__r.Account.PersonMobilePhone,Opportunity__r.Account.PAN_No__c,
                Previous_Outstanding__c,Advanced_Received__c,Amount__c,
                 Assignment__c,Posting_Date__c,Status__c,Bank_Name__c,Clearing_Document_Number__c,Cheque_No__c,Customer_Receipt_Number__c,
                 Cheque_Clearing_Date__c,Document_Clearing_Date__c,Tax_Amount__c,Tax_Code__c,Sp_GL_Indicator__c,Sp_GL_Indicator_Code__c,
                 Reversal_Doc__c,Reversal_Reason__c,Reversal_Reason_Code__c
                 FROM Payment__c where Id =: payId AND RecordType.Name = 'Invoice'];
        //    prodList = [Select Name,Material_Code__c from Product2 where Opportunity__c =: pList[0].Opportunity__c];
        System.debug('pList:: '+pList);
    }
}