force-app/main/default/objects/Account/fields/City_O__c.field-meta.xml
<CustomField>
    <fullName>City_O__c</fullName>
    <label>City O</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <formula>ShippingStreet &amp; &quot;, &quot; &amp;
ShippingCity &amp; &quot;, &quot; &amp;
ShippingState &amp; &quot; - &quot; &amp;
ShippingPostalCode &amp; &quot;, &quot; &amp;
ShippingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Kerla</fullName>
            </value>
            <value>
                <fullName>Northland</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City_O__c.field-meta.xml
<CustomField>
    <fullName>City_O__c</fullName>
    <label>City (O)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Indore</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Visakhapatnam[a][5]</fullName>
            </value>
            <value>
                <fullName>Pimpri-Chinchwad</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
            <value>
                <fullName>Vadodara</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Ludhiana</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Nashik</fullName>
            </value>
            <value>
                <fullName>Faridabad</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Saleable__c.field-meta.xml
<CustomField>
    <fullName>Product_Saleable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Saleable</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tower1__c.field-meta.xml
<CustomField>
    <fullName>Tower1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Advanced_Received__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Received__c</fullName>
    <label>Advanced Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <label>Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Demand_Letter_Date__c.field-meta.xml
<CustomField>
    <fullName>Demand_Letter_Date__c</fullName>
    <label>Demand Letter Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <formula>Product__r.Material_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Material Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/taxInvoiceController.cls
// Test Class : TestTaxInvoiceController
public class taxInvoiceController {
    
    public List<Payment__c> pList {get;set;}
    public List<Account> accList {get;set;}
    public List<Payment__c> pListAmount {get;set;}
    //    public List<Product2> prodList {get;set;}
    public Id payId {get;set;}
    public Decimal AmountAV {get;set;}
    public Decimal AmountGST {get;set;}
    public Decimal AmountTDS {get;set;}
    public Decimal TotalAmt {get;set;}
    public String app2Name {get;set;}
    public String app2pan {get;set;}
    public String app3Name {get;set;}
    public String app3pan {get;set;}
    
    public taxInvoiceController(){
        Id payId = ApexPages.currentPage().getParameters().get('id');
        pList = new List<Payment__c>();
        taxMethod(payId);
    } 
    
    
    public void taxMethod(String payId){
        if(payId != Null){
            pList = [SELECT Id, Name,Opportunity__c, Account__c,Customer_Code__c,Opportunity__r.Project__r.Name,Demand_Letter_Date__c,Due_Date__c,
                     Opportunity__r.Tower1__r.Name,Opportunity__r.Product_Saleable__r.Material_Code__c,Document_Number__c,
                     Opportunity__r.Product_Saleable__r.Name,Opportunity__r.Account.Name,Opportunity__r.Account.Customer_Address__c,
                     Opportunity__r.Account.City_O__c,Opportunity__r.Account.Pincode__c,Opportunity__r.Account.State_Province__c,
                     Opportunity__r.Account.Country__c,Opportunity__r.Account.PersonMobilePhone,Opportunity__r.Account.PAN_No__c,
                    Previous_Outstanding__c,Advanced_Received__c
                     FROM Payment__c where Id =: payId AND RecordType.Name = 'Invoice'];
            //    prodList = [Select Name,Material_Code__c from Product2 where Opportunity__c =: pList[0].Opportunity__c];
            System.debug('pList:: '+pList);
            System.debug('pList[0].Account__c :: '+pList[0].Account__c);
            System.debug('Payment Name :: '+pList[0].Name);
            System.debug('Opportunity related to payment :: '+pList[0].Opportunity__c);
            pListAmount = [SELECT Id, Name,Opportunity__c,Assignment__c,Amount__c from Payment__c where Opportunity__c =: pList[0].Opportunity__c and Name =:pList[0].Name];
            System.debug('pListAmount size ::'+ pListAmount.size());
            System.debug('pListAmount :: '+pListAmount);
            
            if(pListAmount.size() != 0){
                for(Payment__c p:pListAmount){
                    if(p.Assignment__c == 'Ageement Value'){
                        AmountAV = p.Amount__c;
                    }
                    else if(p.Assignment__c == 'GST'){
                        AmountGST = p.Amount__c;
                    }
                    else if(p.Assignment__c == 'TDS'){
                        AmountTDS = p.Amount__c;
                    }
                }
                if(AmountAV != Null && AmountGST != Null && AmountTDS != Null){
                    TotalAmt = AmountAV + AmountGST + AmountTDS;  
                }
                
            }
            System.debug('AmountAV :: '+AmountAV);
            System.debug('AmountGST :: '+AmountGST);
            System.debug('AmountTDS :: '+AmountTDS);
            System.debug('TotalAmt :: '+TotalAmt);
            System.debug('pList[0].Account__c :: '+pList[0].Account__c);
            if(pList[0].Account__c != Null){
                accList = [select id,name,PAN_No__c,ParentId from Account where ParentId =:pList[0].Account__c  limit 2];
                System.debug('accList :: '+accList);
                System.debug('accList size :: '+accList.size());
            }
            if(accList.size() == 1){
                app2Name = accList[0].name;
                app2pan = accList[0].PAN_No__c;
            }
            else if(accList.size() == 2){
                app2Name = accList[0].name;
                app2pan = accList[0].PAN_No__c;
                app3Name = accList[1].name;
                app3pan = accList[1].PAN_No__c;
            }
            
        }
        
    }

}