force-app/main/default/objects/Account/fields/Type_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Interest__c</fullName>
    <label>Type of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Channel_Partner.recordType-meta.xml
<RecordType>
    <fullName>Channel_Partner</fullName>
    <active>true</active>
    <label>Channel Partner</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget ( In Lac)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <displayFormat>{00}</displayFormat>
    <externalId>true</externalId>
    <label>Lead Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner_Name__c</fullName>
    <formula>Owner:User.FirstName &amp; &quot; &quot; &amp; Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Owner Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Location_Interested_in__c.field-meta.xml
<CustomField>
    <fullName>Location_Interested_in__c</fullName>
    <label>Project location Interested in</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <formula>IMAGE( URLsrc__c&amp;&quot;/servlet/servlet.ImageServer?id=&quot;&amp;CASE( Rating,
&quot;Hot&quot;, &quot;015Hn000003A8fa&amp;oid=&quot;&amp;$Organization.Id,
&quot;Warm&quot;, &quot;015Hn000003A8fb&amp;oid=&quot;&amp;$Organization.Id,
&quot;Cool&quot;, &quot;015Hn000003A8fc&amp;oid=&quot;&amp;$Organization.Id,
&quot;015Hn000003A8fc&amp;oid=&quot;&amp;$Organization.Id),&quot;&quot;,22,22)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aspiration</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Purchaser__c.field-meta.xml
<CustomField>
    <fullName>Purchaser__c</fullName>
    <label>Purchaser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Related_Unit__c.field-meta.xml
<CustomField>
    <fullName>Related_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Interest__c</fullName>
    <label>Type of Interest</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/SDO_Lead_Default.recordType-meta.xml
<RecordType>
    <fullName>SDO_Lead_Default</fullName>
    <active>true</active>
    <businessProcess>Sales Lead</businessProcess>
    <description>Standard lead qualification and conversion process.</description>
    <label>Lead</label>
</RecordType>

force-app/main/default/objects/Unit__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Type_of_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LAND</fullName>
    </customValue>
    <customValue>
        <fullName>BTS</fullName>
    </customValue>
    <masterLabel>Type of Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LightningLeadPageController.cls
public with sharing class LightningLeadPageController {
    
    @AuraEnabled(cacheable=true)
    public static User getCurrentPortalUser() {
        return [SELECT Id, Name, ContactId, Contact.Name, AccountId, Account.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Lead> getLeads() {
        User currentUser = getCurrentPortalUser();
        Id channel_Partner = currentUser.AccountId;
        
        // Removed Priority__c entirely.
        return [
            SELECT Id, Name, Phone, Email, Status, Lead_Number__c, Budget__c, 
                   Lead_Owner_Name__c, Type_of_Interest__c, Purchaser__c, 
                   Related_Unit__c, Related_Unit__r.Name, Related_Unit__r.Unit_Cost__c, 
                   Location_Interested_in__c, Project_Type__c, CreatedDate, Rating
            FROM Lead 
            WHERE Channel_Partner__c = :channel_Partner AND Status Not IN ('Converted', 'Lead Lost')
            ORDER BY CreatedDate DESC
            LIMIT 50
        ];
    }

    @AuraEnabled
    public static Lead createLead(String firstName, String lastName, String phone, String email, String budget, String location, String projectType, String typeOfInterest, String purchaser, String rating) {
        
        User currentUser = getCurrentPortalUser();

        Lead newLead = new Lead();
        newLead.FirstName = firstName;
        newLead.LastName = lastName;
        newLead.Phone = phone;
        newLead.Email = email;
        newLead.Budget__c = budget;
        //newLead.Location_Interested_in__c = location;
        newLead.Project_Type__c = projectType;
        newLead.Type_of_Interest__c = typeOfInterest; 
        newLead.Purchaser__c = purchaser; 
        newLead.Rating = rating; 
        
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('SDO_Lead_Default').getRecordTypeId();
        if(recordTypeId != null) { newLead.RecordTypeId = recordTypeId; }
        if (currentUser.AccountId != null) { newLead.Channel_Partner__c = currentUser.AccountId; }
        
        insert as user newLead;
        return newLead;
    }
}