force-app/main/default/objects/Lead/fields/Flat_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Flat_Unit_Cost__c</fullName>
    <label>Flat / Unit Cost (A)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Registration_Charges__c.field-meta.xml
<CustomField>
    <fullName>Registration_Charges__c</fullName>
    <label>Registration Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Society_Charges__c.field-meta.xml
<CustomField>
    <fullName>Society_Charges__c</fullName>
    <label>Society Charges (B)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower(Module)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tower</value>
        </filterItems>
        <filterItems>
            <field>Module__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Leads (Tower)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit(Module)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Unit</value>
        </filterItems>
        <filterItems>
            <field>Module__c.Tower__c</field>
            <operation>equals</operation>
            <valueField>$Source.Tower__c</valueField>
        </filterItems>
        <filterItems>
            <field>Module__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flat_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Flat_Unit_Cost__c</fullName>
    <label>Flat / Unit Cost (A)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Goods_and_Service_Tax_GST__c.field-meta.xml
<CustomField>
    <fullName>Goods_and_Service_Tax_GST__c</fullName>
    <label>Goods and Service Tax (GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Registration_Charges__c.field-meta.xml
<CustomField>
    <fullName>Registration_Charges__c</fullName>
    <label>Registration Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Society_Charges__c.field-meta.xml
<CustomField>
    <fullName>Society_Charges__c</fullName>
    <label>Society Charges (B)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Backend</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit / Apartment</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Opportunities (Unit / Apartment)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Quotes (Unit)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leadConvertAutoCtrl.cls
public without sharing class leadConvertAutoCtrl {
    @InvocableMethod
    public static void assignLeads(List<Id> LeadIds){
		leadConvertAutoCtrl.assignPropertyDetails();        
        LeadStatus cLeadStatus=[Select Id,MasterLabel from LeadStatus where isConverted=true limit 1];
        List<Database.LeadConvert> massLeadConvert=new List<Database.LeadConvert>();
        for(Id currentLead:LeadIds){
            Database.LeadConvert LeadConvert=new Database.LeadConvert();
            LeadConvert.setLeadId(currentLead);
            LeadConvert.setConvertedStatus(cLeadStatus.MasterLabel);
            LeadConvert.setDoNotCreateOpportunity(false);
            massLeadConvert.add(LeadConvert);
        }
        
        if(!massLeadConvert.isEmpty()){
           List<Database.LeadConvertResult> lcr=Database.convertLead(massLeadConvert);
            system.debug('lcr:: '+lcr);
            Set<ID> ids=new Set<ID>();
            for(Id ld:LeadIds){
                ids.add(ld);
            }
            ID accID=[select ConvertedAccountId from lead where id=:ids Limit 1].ConvertedAccountId;
            ID oppId=[select ConvertedOpportunityId  from lead where id=:ids Limit 1].ConvertedOpportunityId;
            List<Opportunity> lstOpps=[select id, name, StageName, Project__c, Unit__c, Tower__c, Flat_Unit_Cost__c,Stamp_Duty__c,Society_Charges__c,Registration_Charges__c,Goods_and_Service_Tax_GST__c from Opportunity where id=:oppId];
            for(Opportunity opp : lstOpps){
                opp.StageName='Proposal/Price Quote';
            }
            update lstOpps;
            system.debug('opps updated');
            
            Integer quoteCount=[Select count() from quote where OpportunityId=:oppId];
            Quote quo=new Quote();
            if(quoteCount==0){
            	for(Opportunity opp : lstOpps){
            		quo.Name=opp.Name+' Quote';
                	quo.OpportunityId=oppId;
                	quo.Project__c=opp.Project__c;
                   
            	}
                insert quo;
            }       
        }
    }
 	
    public static void assignPropertyDetails(){
        
}
}