force-app/main/default/objects/Lead/fields/Purchaser__c.field-meta.xml
<CustomField>
    <fullName>Purchaser__c</fullName>
    <label>Purchaser</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Interest__c</fullName>
    <label>Type of Interest</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type_of_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LAND</fullName>
    </customValue>
    <customValue>
        <fullName>BTS</fullName>
    </customValue>
    <masterLabel>Type of Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadController.cls
public with sharing class LeadController {

    @AuraEnabled(cacheable=true)
    public static List<Lead> getLeads() {

        return [
            SELECT Id, Name, Email, Phone,Status,CreatedDate
            FROM Lead
            ORDER BY LastModifiedDate DESC
       		LIMIT 10
        ];

    }

    @AuraEnabled
    public static void createLead(Map<String,Object> leadData) {

        Lead l = new Lead();

        l.FirstName = (String) leadData.get('FirstName');
        l.LastName = (String) leadData.get('LastName');
        l.Email = (String) leadData.get('Email');
        l.Phone = (String) leadData.get('Phone');
        //l.Company = (String) leadData.get('Company');
        l.Purchaser__c = (String)leadData.get('Purchaser__c');
    	l.Type_of_Interest__c = (String)leadData.get('Type_of_Interest__c');

        insert l;

    }

}