force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Installment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Installment_Amount__c</fullName>
    <label>Installment Amount (AED)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Installment_No__c.field-meta.xml
<CustomField>
    <fullName>Installment_No__c</fullName>
    <label>Installment No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN01</fullName>
                <label>in01</label>
            </value>
            <value>
                <fullName>IN02</fullName>
                <label>in02</label>
            </value>
            <value>
                <fullName>in03</fullName>
            </value>
            <value>
                <fullName>in04</fullName>
            </value>
            <value>
                <fullName>in05</fullName>
            </value>
            <value>
                <fullName>in06</fullName>
            </value>
            <value>
                <fullName>in07</fullName>
            </value>
            <value>
                <fullName>in08</fullName>
            </value>
            <value>
                <fullName>in09</fullName>
            </value>
            <value>
                <fullName>in10</fullName>
            </value>
            <value>
                <fullName>in11</fullName>
            </value>
            <value>
                <fullName>in12</fullName>
            </value>
            <value>
                <fullName>in13</fullName>
            </value>
            <value>
                <fullName>in14</fullName>
            </value>
            <value>
                <fullName>in15</fullName>
            </value>
            <value>
                <fullName>in16</fullName>
            </value>
            <value>
                <fullName>in17</fullName>
            </value>
            <value>
                <fullName>in18</fullName>
            </value>
            <value>
                <fullName>in19</fullName>
            </value>
            <value>
                <fullName>in20</fullName>
            </value>
            <value>
                <fullName>in21</fullName>
            </value>
            <value>
                <fullName>in22</fullName>
            </value>
            <value>
                <fullName>in23</fullName>
            </value>
            <value>
                <fullName>in24</fullName>
            </value>
            <value>
                <fullName>in25</fullName>
            </value>
            <value>
                <fullName>in26</fullName>
            </value>
            <value>
                <fullName>in27</fullName>
            </value>
            <value>
                <fullName>in28</fullName>
            </value>
            <value>
                <fullName>in29</fullName>
            </value>
            <value>
                <fullName>in30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resale Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Plan_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Payment_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan Detail</label>
    <referenceTo>Payment_Plan_Detail__c</referenceTo>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Progressed</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>UnPaid</fullName>
                <isActive>false</isActive>
                <label>UnPaid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentPlanReminderEmailBatch.cls
global class PaymentPlanReminderEmailBatch  implements Database.Batchable<SObject> {
    
   public static String emailBodyTemplate = 
    '<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">' +
    '<p>Dear {1},</p>' +
    '<p>' +
    'I hope you\'re well. This is a friendly reminder that the payment of ' +
    '<strong>AED {2}</strong> for invoice <strong>#{3}</strong> is due on ' +
    '<strong>{4}</strong>.' +
    '</p>' +
    '<p>' +
    'Please let us know if you\'ve already made the payment or if you need any assistance.' +
    '</p>' +
    '<p>Thank you for your attention to this matter!</p>';
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Set<String> statusNotConsiderd = new Set<String>{'Paid'};
            return Database.getQueryLocator([
                SELECT Id, Name, Opportunity__c, Opportunity__r.AccountId, Opportunity__r.Account.Name, Opportunity__r.Primary_Contact__c, 
                Opportunity__r.Account.PersonEmail, Status__c, Invoice_Due_Date__c,Installment_No__c, Installment_Amount__c
                FROM Payment_Plan_Detail__c
                WHERE  Status__c NOT IN :statusNotConsiderd AND Opportunity__r.AccountId != NULL AND
                Invoice_Due_Date__c = :Date.today()
            ]);
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        
        for (Payment_Plan_Detail__c rec : (List<Payment_Plan_Detail__c>)scope) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            email.setSubject('Payment Plan Reminder - Invoice Due Today '+ rec.Installment_No__c);
            
            String emailBody = emailBodyTemplate.replace('{1}', rec.Opportunity__r.Account.Name);
            emailBody = emailBody.replace('{2}', String.valueOf(rec.Installment_Amount__c));   
            emailBody = emailBody.replace('{3}', rec.Installment_No__c);
            emailBody = emailBody.replace('{4}', String.valueOf(rec.Invoice_Due_Date__c));
            
            email.setHTMLbody(emailBody);
            email.setWhatId(rec.Opportunity__r.Account.Id);
            email.setTargetObjectId(rec.Opportunity__r.Primary_Contact__c);
            email.setSaveAsActivity(true);
            email.setToAddresses(new String[] { rec.Opportunity__r.Account.PersonEmail });
            
            emails.add(email);
            
        }
        
        if (!emails.isEmpty()) {
            Messaging.sendEmail(emails);
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        System.debug('Reminder Emails Sent');
    }
}