force-app/main/default/objects/Module__c/fields/Amenity_Title__c.field-meta.xml
<CustomField>
    <fullName>Amenity_Title__c</fullName>
    <description>Amenity Title</description>
    <inlineHelpText>Enter Amenity Title</inlineHelpText>
    <label>Amenity Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Specification_Title__c.field-meta.xml
<CustomField>
    <fullName>Specification_Title__c</fullName>
    <description>Specification Title</description>
    <inlineHelpText>Enter Specification Title</inlineHelpText>
    <label>Specification Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <description>Tower Name</description>
    <inlineHelpText>Enter Tower Name</inlineHelpText>
    <label>Tower Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/UniqueCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueCode__c</fullName>
    <description>Unique code</description>
    <formula>IF(
    RecordType.Name = &apos;Tower&apos;,
    Project__r.Name &amp; &quot;-&quot; &amp; Tower_Name__c,
    IF(
        RecordType.Name = &apos;Wing&apos;,
        Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Wing_Name__c,
        IF(
            RecordType.Name = &apos;Floor&apos;,
            Wing__r.Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Wing__r.Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Wing__r.Wing_Name__c &amp; &quot;-&quot; ,
            IF(
                RecordType.Name = &apos;Unit&apos;,
                Floor__r.Wing__r.Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Floor__r.Wing__r.Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Floor__r.Wing__r.Wing_Name__c &amp; &quot;-&quot;&amp; &quot;-&quot; &amp; Unit_Name__c,
                &apos;&apos;
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unique code</inlineHelpText>
    <label>UniqueCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing_Name__c.field-meta.xml
<CustomField>
    <fullName>Wing_Name__c</fullName>
    <description>Wing Name</description>
    <inlineHelpText>Enter Wing Name</inlineHelpText>
    <label>Wing Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Amenities.recordType-meta.xml
<RecordType>
    <fullName>Amenities</fullName>
    <active>true</active>
    <description>Amenities of project</description>
    <label>Amenities</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Specifications.recordType-meta.xml
<RecordType>
    <fullName>Specifications</fullName>
    <active>true</active>
    <description>Specifications of project</description>
    <label>Specifications</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Tower.recordType-meta.xml
<RecordType>
    <fullName>Tower</fullName>
    <active>true</active>
    <description>Record Type for Project Tower</description>
    <label>Tower</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Wing.recordType-meta.xml
<RecordType>
    <fullName>Wing</fullName>
    <active>true</active>
    <description>Record Type for Project Tower Wing</description>
    <label>Wing</label>
</RecordType>

force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/classes/REIM_GetRelatedDataForProject.cls
public class REIM_GetRelatedDataForProject {
    //The below function is written to get the Tower data to display as related list on project object
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getTowers(String recordId){
        return [select ID, Name, Tower_Name__c,uniquecode__c, Project__c    
                from Module__c where Record_Type_Name__c ='Tower' and Project__c  =: recordId];
    }
    
    //The below function is written to get the Amenities data to display as related list on project object
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getAmenities(String recordId){
        return [select ID, Name, Amenity_Title__c, uniquecode__c,Project__c 
                from Module__c where Record_Type_Name__c='Amenities' 
                and Project__c =: recordId];
    }
    //The below function is written to get the Specification data per project to display as it related list on project object
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getSpecifications(String recordId){
        return [select ID, Name, Specification_Title__c, uniquecode__c,Project__c 
                from Module__c where Record_Type_Name__c='Specifications' 
                and Project__c =: recordId];
    }
    //The below function is written to get the WING data per project to display as it related list on project object
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getWings(String recordId){
        return [select ID, Name, Wing_Name__c, uniquecode__c,Project__c
                from Module__c where Record_Type_Name__c='Wing' 
                and Project__c =: recordId];
    }
}