force-app/main/default/objects/Module__c/fields/Amenity_Description__c.field-meta.xml
<CustomField>
    <fullName>Amenity_Description__c</fullName>
    <description>Amenity Description</description>
    <inlineHelpText>Enter Amenity Description</inlineHelpText>
    <label>Amenity Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Amenity_Image__c.field-meta.xml
<CustomField>
    <fullName>Amenity_Image__c</fullName>
    <description>Amenity Image</description>
    <inlineHelpText>Add Amenity Image</inlineHelpText>
    <label>Amenity Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Amenity_Title__c.field-meta.xml
<CustomField>
    <fullName>Amenity_Title__c</fullName>
    <description>Amenity Title</description>
    <inlineHelpText>Enter Amenity Title</inlineHelpText>
    <label>Amenity Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Specification_Description__c.field-meta.xml
<CustomField>
    <fullName>Specification_Description__c</fullName>
    <description>Specification Description</description>
    <inlineHelpText>Enter Specification Description</inlineHelpText>
    <label>Specification Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Specification_Image__c.field-meta.xml
<CustomField>
    <fullName>Specification_Image__c</fullName>
    <label>Specification Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Specification_Title__c.field-meta.xml
<CustomField>
    <fullName>Specification_Title__c</fullName>
    <description>Specification Title</description>
    <inlineHelpText>Enter Specification Title</inlineHelpText>
    <label>Specification Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Amenities.recordType-meta.xml
<RecordType>
    <fullName>Amenities</fullName>
    <active>true</active>
    <description>Amenities of project</description>
    <label>Amenities</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Specifications.recordType-meta.xml
<RecordType>
    <fullName>Specifications</fullName>
    <active>true</active>
    <description>Specifications of project</description>
    <label>Specifications</label>
</RecordType>

force-app/main/default/objects/Project__c/fields/Amenity_Header__c.field-meta.xml
<CustomField>
    <fullName>Amenity_Header__c</fullName>
    <description>Amenity Header</description>
    <inlineHelpText>Enter Amenity Header.</inlineHelpText>
    <label>Amenity Header</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Specification_Header__c.field-meta.xml
<CustomField>
    <fullName>Specification_Header__c</fullName>
    <description>Specification Header</description>
    <inlineHelpText>Enter Specification Header</inlineHelpText>
    <label>Specification Header</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/reimAmenitiesAndSpecificationContoller.cls
public with sharing class reimAmenitiesAndSpecificationContoller {

        @AuraEnabled(cacheable=true)
        public static List<Module__c> getAmenities(String projectId) {
            Id amenRecordTypeId = Schema.SObjectType.Module__c.getRecordTypeInfosByName().get('Amenities').getRecordTypeId();
system.debug('AmenRecordTypeId'+amenRecordTypeId);

            String proId = projectId;
            system.debug('proId'+proId);
            List<Module__c> amenitiesLst = new List<Module__c>();

    amenitiesLst = [
        SELECT Id, Amenity_Title__c, Amenity_Description__c,Amenity_Image__c,Project__r.Amenity_Header__c 
        FROM Module__c
        WHERE Project__c = :proId
        AND RecordTypeId = :amenRecordTypeId
    ];

    System.debug('Amenities are: ' + amenitiesLst);
    return amenitiesLst;
        }

        @AuraEnabled(cacheable=true)
        public static List<Module__c> getSpecifications(String projectId) {
            Id specRecordTypeId = Schema.SObjectType.Module__c.getRecordTypeInfosByName().get('Specifications').getRecordTypeId();
            system.debug('specRecordTypeId'+specRecordTypeId); 
            String proId = projectId;
            system.debug('proId'+proId);
            List<Module__c> specificationLst = new  List<Module__c>();

            specificationLst = [Select Id,Specification_Title__c, Specification_Description__c,Specification_Image__c,Project__r.Specification_Header__c From Module__c where Project__c=:proId AND   RecordTypeId = :specRecordTypeId];

            system.debug('specificationLst are ===>'+specificationLst);

            return specificationLst;

     
        }
    }