force-app/main/default/objects/Module__c/fields/Balcony__c.field-meta.xml
<CustomField>
    <fullName>Balcony__c</fullName>
    <description>Balcony</description>
    <inlineHelpText>Balcony area in Sq Ft</inlineHelpText>
    <label>Balcony</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <description>Carpet Area</description>
    <inlineHelpText>Carpet Area in Sq Ft</inlineHelpText>
    <label>Carpet Area</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Facing__c.field-meta.xml
<CustomField>
    <fullName>Facing__c</fullName>
    <label>Facing</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be displayed when Record type is unit, to select floor.This is self lookup</description>
    <inlineHelpText>Select Floor</inlineHelpText>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Floor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Modules2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Floor_Name__c.field-meta.xml
<CustomField>
    <fullName>Floor_Name__c</fullName>
    <description>Floor Name</description>
    <inlineHelpText>Enter Floor Name</inlineHelpText>
    <label>Floor Name</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/has_wing__c.field-meta.xml
<CustomField>
    <fullName>has_wing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this field indicates whether the tower has wing or not</description>
    <label>Do the Tower have wings?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Price_Per_Sqft__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Sqft__c</fullName>
    <description>Price Per Sqft</description>
    <inlineHelpText>Enter Price Per Sq ft</inlineHelpText>
    <label>Price Per Sqft</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total Price</description>
    <inlineHelpText>Total Price</inlineHelpText>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup on Module__c . This is for Tower which will be displayed on Wing Record Type</description>
    <inlineHelpText>Select Tower</inlineHelpText>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Wings</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <description>Tower Name</description>
    <inlineHelpText>Enter Tower Name</inlineHelpText>
    <label>Tower Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/UniqueCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueCode__c</fullName>
    <description>Unique code</description>
    <formula>IF(
    RecordType.Name = &apos;Tower&apos;,
    Project__r.Name &amp; &quot;-&quot; &amp; Tower_Name__c,
    IF(
        RecordType.Name = &apos;Wing&apos;,
        Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Wing_Name__c,
        IF(
            RecordType.Name = &apos;Floor&apos;,
            Wing__r.Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Wing__r.Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Wing__r.Wing_Name__c &amp; &quot;-&quot; ,
            IF(
                RecordType.Name = &apos;Unit&apos;,
                Floor__r.Wing__r.Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Floor__r.Wing__r.Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Floor__r.Wing__r.Wing_Name__c &amp; &quot;-&quot;&amp; &quot;-&quot; &amp; Unit_Name__c,
                &apos;&apos;
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unique code</inlineHelpText>
    <label>UniqueCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Bathroom_Count__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bathroom_Count__c</fullName>
    <description>Unit Bathroom Count</description>
    <inlineHelpText>Unit Bathroom Count</inlineHelpText>
    <label>Unit Bathroom Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Bedroom_Count__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bedroom_Count__c</fullName>
    <description>Unit Bedroom Count</description>
    <inlineHelpText>Enter Unit Bedroom Count</inlineHelpText>
    <label>Unit Bedroom Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Description__c.field-meta.xml
<CustomField>
    <fullName>Unit_Description__c</fullName>
    <description>Unit Description</description>
    <inlineHelpText>Enter Unit Description</inlineHelpText>
    <label>Unit Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <description>Unit Name</description>
    <inlineHelpText>Enter Unit Name</inlineHelpText>
    <label>Unit Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Plan_Image__c.field-meta.xml
<CustomField>
    <fullName>Unit_Plan_Image__c</fullName>
    <description>Unit Plan Image</description>
    <inlineHelpText>Add Unit Plan Image</inlineHelpText>
    <label>Unit Plan Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Size__c.field-meta.xml
<CustomField>
    <fullName>Unit_Size__c</fullName>
    <description>Unit Size</description>
    <inlineHelpText>Select Unit Size</inlineHelpText>
    <label>Unit Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <description>Unit Status</description>
    <inlineHelpText>Select Unit Status</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <description>Unit Type</description>
    <inlineHelpText>Select Unit Type</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Block</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Vastu__c.field-meta.xml
<CustomField>
    <fullName>Vastu__c</fullName>
    <label>Unit Vastu</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North-East</fullName>
            </value>
            <value>
                <fullName>North-West</fullName>
            </value>
            <value>
                <fullName>South-East</fullName>
            </value>
            <value>
                <fullName>South-West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing__c.field-meta.xml
<CustomField>
    <fullName>Wing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to show Wing when record Type is Floor. Self Lookup</description>
    <inlineHelpText>Select Wing</inlineHelpText>
    <label>Wing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Wing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Modules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing_Name__c.field-meta.xml
<CustomField>
    <fullName>Wing_Name__c</fullName>
    <description>Wing Name</description>
    <inlineHelpText>Enter Wing Name</inlineHelpText>
    <label>Wing Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Floor.recordType-meta.xml
<RecordType>
    <fullName>Floor</fullName>
    <active>true</active>
    <description>Record Type for Floor</description>
    <label>Floor</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Tower.recordType-meta.xml
<RecordType>
    <fullName>Tower</fullName>
    <active>true</active>
    <description>Record Type for Project Tower</description>
    <label>Tower</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>Record Type for Unit</description>
    <label>Unit</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Wing.recordType-meta.xml
<RecordType>
    <fullName>Wing</fullName>
    <active>true</active>
    <description>Record Type for Project Tower Wing</description>
    <label>Wing</label>
</RecordType>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Reim_FilterFor_TowerAndFloors.cls
public class Reim_FilterFor_TowerAndFloors {
    /*Dev : Sushant S, Below 3 methods are used in 'Reim_showFloorAndUnits' Component*/
    	@AuraEnabled(cacheable=true)
    public static List<Module__c> getTowersDataUponFilter
		( String projId,String towerId,String wing, String SizeType,String Vastu, String Facing,String UnitStatus) {
			String query=' ';
            String query1=' ';
            if(wing == 'All' && SizeType == 'All' && Vastu == 'All' && Facing == 'All' && UnitStatus == 'All'){
               query1='Select Id, Project__c,  Record_Type_Name__c, Floor__c, Floor__r.Floor_Name__c, Tower__c,Tower__r.Tower_Name__c,Wing__c, Wing__r.Wing_Name__c, UniqueCode__c,Unit_Status__c, Unit_Name__c, Unit_Type__c,Vastu__c,Unit_Size__c,Facing__c from module__c WHERE Record_Type_Name__c=\'Unit\' AND Project__c=:projId AND Tower__c!=:towerId ';
            }
            else
            {
                query='Select Id, Project__c,  Record_Type_Name__c, Floor__c, Floor__r.Floor_Name__c, Tower__c,Tower__r.Tower_Name__c,Wing__c, Wing__r.Wing_Name__c, UniqueCode__c,Unit_Status__c, Unit_Name__c, Unit_Type__c,Vastu__c,Unit_Size__c,Facing__c from module__c WHERE (Record_Type_Name__c=\'Unit\' AND Project__c=:projId AND Tower__c=:towerId) AND (';
            }
            
		List<String> whereClauses = new List<String>();
            System.debug(query1.length());
            System.debug(query.length());
		if (wing != 'All') {
			whereClauses.add(' Wing__r.Wing_Name__c != :wing ');
		}
		if (SizeType != 'All') {
			whereClauses.add(' Unit_Size__c != :SizeType ');
		}
		if (Vastu != 'All') {
			whereClauses.add(' Vastu__c != :Vastu ');
		}
		if (Facing != 'All') {
			whereClauses.add(' Facing__c != :Facing ');
		}
		if (UnitStatus != 'All') {
			whereClauses.add(' Unit_Status__c != :UnitStatus ');
		}
            
        String condition=String.join(whereClauses, ' OR ');
            system.debug(condition);
            //System.debug(query);
            //System.debug(Database.query(query+condition));
            System.debug(query+condition);
            String resultQuery;
            if(query1.length()>=5){
                resultQuery= query1;
            }
            else if(query1.length()<=5){
                resultQuery=query+condition+')';
            }
             return Database.query(resultQuery);     
	}
    
        @AuraEnabled(cacheable=true)
    public static List<Module__c> getFloorsDataUponFilter( String towerId){
        List<Module__c> lstFloors=[Select id,Project__c,Tower__c,Floor_Name__c,has_wing__c from module__c where Tower__c=:towerId and Record_Type_Name__c='Floor' order by Floor_Name__c DESC];
        
        return lstFloors; 
    }
    
@AuraEnabled(cacheable=true)
    public static Map<String,List<Module__c>> getStaticUnitsDataToDisplay( String towerId){
        List<Module__c> lstUnits=[Select Id, Project__c,  Record_Type_Name__c, Floor__c, Floor__r.Floor_Name__c, Tower__c,Tower__r.Tower_Name__c,Wing__c, Wing__r.Wing_Name__c, UniqueCode__c,Unit_Status__c, Unit_Name__c, Unit_Type__c,Vastu__c,Unit_Size__c,Facing__c from module__c WHERE Record_Type_Name__c='Unit' AND Tower__c=:towerId order by Unit_Name__c DESC];
		System.debug(lstUnits);
        List<Module__c> floorList= Reim_FilterFor_TowerAndFloors.getFloorsDataUponFilter(towerId);
        System.debug(floorList);
     
        Map<String,List<Module__c>> mapUnits=new Map<String,List<Module__c>>();
        
        for(Module__c floors:floorList){
            List<Module__c> tempList=new List<Module__c>();
            for(Module__c units:lstUnits){
            	if(floors.Floor_Name__c==units.Floor__r.Floor_Name__c){ 
                	tempList.add(units);
            	}    
        }
           		mapUnits.put(String.valueOf(floors.id),tempList);
        }
        system.debug(mapUnits);
        return mapUnits; 
    }
    
    /*Dev : Sushant S, */
    @AuraEnabled(cacheable=true)
    public static String getTowerName( String towerId){
        List<Module__c> lstTowers=[Select id,Tower_Name__c from module__c where id=: towerId and Record_Type_Name__c='Tower'];
        String towerName;
        for(Module__c twr : lstTowers){
            towerName=twr.Tower_Name__c;
        }
        return towerName; 
    }
    
        @AuraEnabled(cacheable=true)
    public static Id getProjectId( String towerId){
        List<Module__c> lstTowers=[Select id,Tower_Name__c,Project__c from module__c where id=: towerId and Record_Type_Name__c='Tower'];
        Id projectId;
        for(Module__c twr : lstTowers){
            projectId= twr.Project__c;
        }
        system.debug(projectId);
        return projectId; 
    }
    
        @AuraEnabled(cacheable=true)
    public static Integer getAvailableUnitsPerTower( String towerId){
        return [Select count() FROM Module__c where Record_Type_Name__c='Unit' and tower__c=:towerId AND Unit_Status__c ='Available'];
    }
    
        @AuraEnabled(cacheable=true)
    public static List<Module__c> getUnitBluePrintData(String unitId) {
        List<Module__c> unitData = [Select Id,Tower__c,Unit_Name__c,Floor__r.Floor_Name__c,Unit_Size__c,Unit_Type__c,Unit_Plan_Image__c,Unit_Description__c, Unit_Bedroom_Count__c,Unit_Bathroom_Count__c,Total_Price__c, Price_Per_Sqft__c,Floor__r.Wing__r.Tower__r.Tower_Name__c,Unit_Status__c,Floor__r.Wing__r.Wing_Name__c,Carpet_Area__c, Balcony__c,Name,UniqueCode__c  
                        from Module__c where Id=: unitId AND Record_Type_Name__c='Unit'];
        
        System.debug('openUnit=====>' + unitData);
        return unitData;
        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getUnitsPerFloor_BluePrintData(String floorId) {
        List<Module__c> unitsData = [Select Id,Unit_Name__c,Floor__r.Floor_Name__c,Unit_Size__c,Unit_Type__c,Unit_Plan_Image__c,Unit_Description__c, Unit_Bedroom_Count__c,Unit_Bathroom_Count__c,Total_Price__c, Price_Per_Sqft__c,Floor__r.Wing__r.Tower__r.Tower_Name__c,Unit_Status__c,Floor__r.Wing__r.Wing_Name__c,Carpet_Area__c, Balcony__c 
                        from Module__c where Floor__c=: FloorId AND Record_Type_Name__c='Unit'];
        
        System.debug('openUnit=====>' + unitsData.size());
        return unitsData;      
    }
    
    @AuraEnabled(cacheable=true)
        public static Map<ID, String> getRelatedFilesByRecordId(String recordId) {
            // Get record file IDs        
            List<ContentDocumentLink> files = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId];
            List<ID> fileIDs = new List<ID>();
            for (ContentDocumentLink docLink : files) {
                fileIDs.add(docLink.ContentDocumentId);
            }
     
            List<ContentVersion> docs = [SELECT ContentDocumentId, FileExtension, Title,VersionDataUrl 
                FROM ContentVersion WHERE ContentDocumentId IN : fileIDs];
            Map<ID, String> mapIdTitle = new Map<ID, String>();
            for (ContentVersion docLink : docs) {
                mapIdTitle.put(docLink.ContentDocumentId, docLink.VersionDataUrl);
            }
            return mapIdTitle;
        }
    
    @AuraEnabled(cacheable=true)
    public static String getTowerId_ForUnitBluePrint( String unitId){
        List<Module__c> lstUnit=[Select id,Tower__c,Project__c from module__c where id=: unitId and Record_Type_Name__c='Unit'];
        String towerId;
        for(Module__c unit : lstUnit){
            towerId= unit.Tower__c;
        }
        system.debug(towerId);
        return towerId; 
    }
    
        @AuraEnabled(cacheable=true)
    public static String getTowerId_ForFloorBluePrint( String floorId){
        List<Module__c> lstFloors=[Select id,Tower__c,Floor_Name__c from module__c where id=: floorId and Record_Type_Name__c='Floor'];
        String towerId;
        for(Module__c floor : lstFloors){
            towerId= floor.Tower__c;
        }
        system.debug(towerId);
        return towerId; 
    }
}