force-app/main/default/objects/Module__c/fields/Balcony__c.field-meta.xml
<CustomField>
    <fullName>Balcony__c</fullName>
    <description>Balcony</description>
    <inlineHelpText>Balcony area in Sq Ft</inlineHelpText>
    <label>Balcony</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <description>Carpet Area</description>
    <inlineHelpText>Carpet Area in Sq Ft</inlineHelpText>
    <label>Carpet Area</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be displayed when Record type is unit, to select floor.This is self lookup</description>
    <inlineHelpText>Select Floor</inlineHelpText>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Floor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Modules2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Floor_Image__c.field-meta.xml
<CustomField>
    <fullName>Floor_Image__c</fullName>
    <description>Floor Image</description>
    <inlineHelpText>Add Floor Image</inlineHelpText>
    <label>Floor Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Floor_Name__c.field-meta.xml
<CustomField>
    <fullName>Floor_Name__c</fullName>
    <description>Floor Name</description>
    <inlineHelpText>Enter Floor Name</inlineHelpText>
    <label>Floor Name</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Price_Per_Sqft__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Sqft__c</fullName>
    <description>Price Per Sqft</description>
    <inlineHelpText>Enter Price Per Sq ft</inlineHelpText>
    <label>Price Per Sqft</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total Price</description>
    <inlineHelpText>Total Price</inlineHelpText>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup on Module__c . This is for Tower which will be displayed on Wing Record Type</description>
    <inlineHelpText>Select Tower</inlineHelpText>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Wings</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <description>Tower Name</description>
    <inlineHelpText>Enter Tower Name</inlineHelpText>
    <label>Tower Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/UniqueCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueCode__c</fullName>
    <description>Unique code</description>
    <formula>IF(
    RecordType.Name = &apos;Tower&apos;,
    Project__r.Name &amp; &quot;-&quot; &amp; Tower_Name__c,
    IF(
        RecordType.Name = &apos;Wing&apos;,
        Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Wing_Name__c,
        IF(
            RecordType.Name = &apos;Floor&apos;,
            Wing__r.Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Wing__r.Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Wing__r.Wing_Name__c &amp; &quot;-&quot; ,
            IF(
                RecordType.Name = &apos;Unit&apos;,
                Floor__r.Wing__r.Tower__r.Project__r.Name &amp; &quot;-&quot; &amp; Floor__r.Wing__r.Tower__r.Tower_Name__c &amp; &quot;-&quot; &amp; Floor__r.Wing__r.Wing_Name__c &amp; &quot;-&quot;&amp; &quot;-&quot; &amp; Unit_Name__c,
                &apos;&apos;
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unique code</inlineHelpText>
    <label>UniqueCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Bathroom_Count__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bathroom_Count__c</fullName>
    <description>Unit Bathroom Count</description>
    <inlineHelpText>Unit Bathroom Count</inlineHelpText>
    <label>Unit Bathroom Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Bedroom_Count__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bedroom_Count__c</fullName>
    <description>Unit Bedroom Count</description>
    <inlineHelpText>Enter Unit Bedroom Count</inlineHelpText>
    <label>Unit Bedroom Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Description__c.field-meta.xml
<CustomField>
    <fullName>Unit_Description__c</fullName>
    <description>Unit Description</description>
    <inlineHelpText>Enter Unit Description</inlineHelpText>
    <label>Unit Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <description>Unit Name</description>
    <inlineHelpText>Enter Unit Name</inlineHelpText>
    <label>Unit Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Plan_Image__c.field-meta.xml
<CustomField>
    <fullName>Unit_Plan_Image__c</fullName>
    <description>Unit Plan Image</description>
    <inlineHelpText>Add Unit Plan Image</inlineHelpText>
    <label>Unit Plan Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Size__c.field-meta.xml
<CustomField>
    <fullName>Unit_Size__c</fullName>
    <description>Unit Size</description>
    <inlineHelpText>Select Unit Size</inlineHelpText>
    <label>Unit Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <description>Unit Status</description>
    <inlineHelpText>Select Unit Status</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <description>Unit Type</description>
    <inlineHelpText>Select Unit Type</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Block</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing__c.field-meta.xml
<CustomField>
    <fullName>Wing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to show Wing when record Type is Floor. Self Lookup</description>
    <inlineHelpText>Select Wing</inlineHelpText>
    <label>Wing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Wing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Modules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing_Name__c.field-meta.xml
<CustomField>
    <fullName>Wing_Name__c</fullName>
    <description>Wing Name</description>
    <inlineHelpText>Enter Wing Name</inlineHelpText>
    <label>Wing Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Floor.recordType-meta.xml
<RecordType>
    <fullName>Floor</fullName>
    <active>true</active>
    <description>Record Type for Floor</description>
    <label>Floor</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Tower.recordType-meta.xml
<RecordType>
    <fullName>Tower</fullName>
    <active>true</active>
    <description>Record Type for Project Tower</description>
    <label>Tower</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>Record Type for Unit</description>
    <label>Unit</label>
</RecordType>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/reimModuleController.cls
public class reimModuleController {
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getTowers(String ProjectId) {
        ID proId=ProjectId;
        Id towerRecordTypeId = Schema.SObjectType.Module__c.getRecordTypeInfosByName().get('Tower').getRecordTypeId();
        system.debug('towerRecordTypeId'+towerRecordTypeId);        
        List<Module__c> modTowerRec = new List<Module__c>(); 
        
                modTowerRec = [SELECT Id, Name, Tower_Name__c, Project__c, Project__r.Name, UniqueCode__c FROM Module__c WHERE Project__c = :proId AND RecordTypeId = :towerRecordTypeId ORDER BY Tower_Name__c ASC];
                System.debug('Module Towers=====>' + modTowerRec.size());
                return modTowerRec;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getWings(String ProjectId,String towerName) {
       
        String proId = ProjectId;
        String twrName= towerName;
        List<Module__c> modWingRec = new List<Module__c>(); 
        modWingRec = [Select Id,Wing_Name__c,Tower__r.Tower_Name__c,UniqueCode__c,Tower__r.UniqueCode__c,Tower__r.Project__c FROM Module__c WHERE Tower__r.Project__c = :proId AND Tower__r.Tower_Name__c =:twrName ];
        System.debug('getWings=====>' + modWingRec);
        return modWingRec;
 
        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getFloors(String towerName) {  
        String twrName = towerName;
        List<Module__c> modFloorRec = new List<Module__c>(); 
        modFloorRec = [Select Id,Floor_Name__c,UniqueCode__c,Wing__r.UniqueCode__c,Wing__r.Tower__r.Project__c FROM Module__c WHERE  Wing__r.Tower__r.Tower_Name__c =:twrName ];
        System.debug('getFloors=====>' + modFloorRec);
        return modFloorRec;        
    }
    
     @AuraEnabled(cacheable=true)
    public static List<Module__c> getUnits(String ProjectId, String floorUniqCode) {
       
        String proId = ProjectId;
        
        String flooruniquecode = floorUniqCode;
        List<Module__c> modUnitRec = new List<Module__c>(); 
        modUnitRec = [Select Id,Unit_Name__c    ,UniqueCode__c,Floor__r.UniqueCode__c,Floor__r.Wing__r.Tower__r.Project__c FROM Module__c WHERE Floor__r.Wing__r.Tower__r.Project__c = :proId AND Floor__r.UniqueCode__c =:floorUniqCode ];
        System.debug('getUnits=====>' + modUnitRec);
        return modUnitRec;
 
        
    }
      
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getUnitsByFloor(String wingtowerId) {
        String wtowerId = wingtowerId;
        
        Map<String, Object> floorUnitMap = new Map<String, Object>();
        
        List<Module__c> modUnitRec = [
            SELECT Id, Unit_Name__c, Unit_Status__c, Floor__c, Floor__r.Floor_Name__c
            FROM Module__c
            WHERE Floor__r.Wing__r.Tower__c = :wtowerId
        ORDER BY Floor__r.Floor_Name__c DESC,Unit_Name__c ASC
        ];
        
        for (Module__c module : modUnitRec) {
            String floorId = module.Floor__c;
            String floorName = String.valueof(module.Floor__r.Floor_Name__c);
            String unitName = module.Unit_Name__c;
            String unitStatus = module.Unit_Status__c;
            
            if (!floorUnitMap.containsKey(floorName)) {
                floorUnitMap.put(floorName, new Map<String, String>());
            }
            
            ((Map<String, String>)floorUnitMap.get(floorName)).put(unitName, unitStatus);
        }
        
        System.debug('Floor Unit Map: ' + floorUnitMap);
        return floorUnitMap;
    }
    
@AuraEnabled(cacheable=true)
    public static List<Module__c> openFloors(String towerId, Integer FloorName) {
       String twrId = towerId;
       Integer flrName = FloorName;
        List<Module__c> modFloorRec = new List<Module__c>(); 
        modFloorRec = [Select Id,Unit_Name__c,Floor__r.Floor_Name__c,Floor__r.Floor_Image__c,Unit_Status__c  from Module__c where Floor__r.Wing__r.Tower__c=: towerId AND Floor__r.Floor_Name__c=: flrName ORDER BY Unit_Name__c ASC];
        System.debug('openFloors=====>' + modFloorRec);
        return modFloorRec;
 
        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Module__c> openUnit(String towerId, String unitName) {
       String twrId = towerId;
       String uName = unitName;
        List<Module__c> modFloorRec = new List<Module__c>(); 
        modFloorRec = [Select Id,Unit_Name__c,Floor__r.Floor_Name__c,Unit_Size__c,Unit_Type__c,Unit_Plan_Image__c,Unit_Description__c, Unit_Bedroom_Count__c,Unit_Bathroom_Count__c,Total_Price__c, Price_Per_Sqft__c,Floor__r.Wing__r.Tower__r.Tower_Name__c,Unit_Status__c,Floor__r.Wing__r.Wing_Name__c,Carpet_Area__c, Balcony__c 
                        from Module__c where Floor__r.Wing__r.Tower__c=: towerId AND Unit_Name__c=: uName ORDER BY Unit_Name__c ASC];
        System.debug('openUnit=====>' + modFloorRec);
        return modFloorRec;
        
    }

    /* Dev : Sushant Salunkhe 
    Code to get the list of available unit on the Floor Plan page for every Tower
    */
    @AuraEnabled(cacheable=true)
    public static Integer getAvailableUnitsPerTower(String towerId) {
        String twrId = towerId;
         List<Module__c> modFloorRec = new List<Module__c>(); 
         modFloorRec = [Select Id,Floor__r.Wing__r.Tower__r.Tower_Name__c,Unit_Status__c,Floor__r.Wing__r.Wing_Name__c from Module__c 
                        where Floor__r.Wing__r.Tower__c=: towerId and  Unit_Status__c='Available' ORDER BY Unit_Name__c ASC];
         System.debug('openUnit=====>' + modFloorRec);
         return modFloorRec.size();
         
     }
   
}