force-app/main/default/objects/Module__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <description>Carpet Area</description>
    <inlineHelpText>Carpet Area in Sq Ft</inlineHelpText>
    <label>Carpet Area</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup on Module__c . This is for Tower which will be displayed on Wing Record Type</description>
    <inlineHelpText>Select Tower</inlineHelpText>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Wings</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>Record Type for Unit</description>
    <label>Unit</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Backend</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Payment_Plan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Line__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Payment Plan Line</relationshipLabel>
    <relationshipName>Payment_Plan_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tower__c.Project__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>Project Address</description>
    <inlineHelpText>Enter Project Address</inlineHelpText>
    <label>Project Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Agreement_Value_w_o_Tax__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_w_o_Tax__c</fullName>
    <formula>IF( AND(ISBLANK(Approved_Discount__c) , ISBLANK(Subvention_Cost__c)) , Agreement_Value__c , (Agreement_Value__c - Approved_Discount__c + Subvention_Cost__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Value(w/o Tax)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Approved_Discount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Discount__c</fullName>
    <label>Approved Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <label>Saleable Area</label>
    <summarizedField>QuoteLineItem.Quantity</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Unit_No__c</field>
        <operation>equals</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST(Flat)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Other_Charges__c.field-meta.xml
<CustomField>
    <fullName>Other_Charges__c</fullName>
    <label>Other Charges</label>
    <summarizedField>QuoteLineItem.Sub_Total__c</summarizedField>
    <summaryFilterItems>
        <field>QuoteLineItem.Unit_No__c</field>
        <operation>lessThan</operation>
        <value>3</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <formula>Project__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scanning_Charges__c.field-meta.xml
<CustomField>
    <fullName>Scanning_Charges__c</fullName>
    <label>Scanning Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <label>Stamp Duty</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Unit_Cost_With_Discount__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_With_Discount__c</fullName>
    <formula>Unit_Cost__c -  Approved_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <formula>If(Product_Family__c = &apos;Saleable Unit&apos;,PricebookEntry.Registration_Charges__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Scanning_Charges__c.field-meta.xml
<CustomField>
    <fullName>Scanning_Charges__c</fullName>
    <formula>IF(  ISPICKVAL(Product2.Family, &apos;Saleable Unit&apos;), PricebookEntry.Scanning_Charges__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scanning Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Stamp_Duty__c.field-meta.xml
<CustomField>
    <fullName>Stamp_Duty__c</fullName>
    <formula>If(Product_Family__c = &apos;Saleable Unit&apos;,PricebookEntry.Stamp_Duty__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stamp Duty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PriceSheetCreateController.cls
/*
** ____________________________________________________________________________________________
** Created by	:   Akash Pawar
** Created Date	:   00/11/2020 
** Company Name	: 	Stetig Consulting Pvt Ltd
** ============================================================================================
** Description	: 	Controller of pricesheet create vf page. This code for create pricesheet.
** ____________________________________________________________________________________________
*/

public class PriceSheetCreateController {
    
    public PriceSheetWrapper objPriceSheetWrapper{get; set;}
    private String parentId;
    public list<Payment_Plan_Line__c> lstPaymentLine{get;set;}
    public Boolean pdfMode{get; set;}
    public String paymentPlanId{get; set;}
    public List<Payment_Plan__c> lstPaymentPlanOption{get; set;}
    Public  String flag; 
    String pdfName;
    /******************************************Constructor**********************************/
    public PriceSheetCreateController(){}
    public void PriceSheetCreate() {
        string Qid = ApexPages.currentPage().getParameters().get('Qid');
        
          pdfMode = True;
        if(Qid != NULL && Qid != ''){
            Quote quote =  [Select Id, Name from Quote where ID =: Qid];
            // Quote quote = (Quote)controller.getRecord();
            if(quote != NULL){
                system.debug('quote'+quote);
                parentId = quote.Id;
                 pdfMode = True;
                //String pageMode = ApexPages.currentPage().getParameters().get('pdfMode');
                // paymentPlanId = ApexPages.currentPage().getParameters().get('paymentPlanId');
                pdfMode = true;
                lstPaymentPlanOption = new List<Payment_Plan__c>();
                    for(Payment_Plan__c objPaymentPlan : [select Id, Name from Payment_Plan__c where Quote__c =: parentId ORDER BY CreatedDate DESC]){
                        lstPaymentPlanOption.add(objPaymentPlan);
                         system.debug('Inside objPaymentPlan'+objPaymentPlan);
                    }
                    if(lstPaymentPlanOption != NULL && !lstPaymentPlanOption.isEmpty()){
                        paymentPlanId = lstPaymentPlanOption[0].Id;
                         system.debug('Inside lstPaymentPlanOption'+lstPaymentPlanOption);
                    }
               
                if(String.isNotBlank(paymentPlanId)){
                    system.debug('Inside paymentPlanId'+paymentPlanId);
                    //initialiseList();
                    createPDF();
                }
            }
            }
        }
    //This method is used to save the Pricesheet into the attachment under the Quote record.
    public void createPDF(){
        pdfMode = true;
        initialiseList();
        string fileName = pdfName+ ' '+'-Pricesheet.pdf';
        //Apexpages.currentPage().getHeaders().put('content-disposition', 'attachemnt; filename='+fileName);
        if(ApexPages.currentPage().getParameters().get('flag') != 'true'){
        createAttachment(parentId, paymentPlanId, pdfName, fileName);
        }
    }
    
    public void createAttachment(String parentId, String paymentPlanId, String pdfName, string fileName){
      flag =  ApexPages.currentPage().getParameters().get('flag');
        system.debug('flag'+flag);
        if(flag == 'false' || flag == NULL){
             system.debug('Inside'+flag);
            flag = 'true';
        PageReference objPageReference = new PageReference('/apex/PriceSheetCreate?Qid='+parentId+'&pdfMode=true&paymentPlanId='+paymentPlanId+'&flag='+flag);
        Blob pdfBody = (Test.isRunningTest()?Blob.valueOf('test'):objPageReference.getContentAsPDF());
       
        Attachment attach = new Attachment();
        attach.Body = pdfBody;
        // add the user entered name
        string st = pdfName+ ' '+'-Pricesheet'+ ''+System.today().format() + '.pdf';
        attach.Name = st;
        attach.IsPrivate = false;
        // attach the pdf to the Quote
        attach.ParentId = parentId;
        list<Attachment> listA = new list<Attachment>([Select id, Name, parentId from attachment where Name =:st and parentId =:parentId]);
              system.debug('Insode listA'+listA);
        if(listA.size()<=0){
            insert attach;
            system.debug('Insode Attach'+attach);
            //Apexpages.currentPage().getHeaders().put('content-disposition', 'attachemnt; filename='+fileName);
        }  
        }
    }
    
    //Method to initialize the Wrapper instance with and Quote Line Items. 
    private void initialiseList(){
        List<Quote> lstQuote = new List<Quote>();
        lstQuote = [select Id, Name, GST__c, Unit_Cost_With_Discount__c, Other_Charges__c,Project__r.Name, Opportunity.Project__r.Terms_and_Conditions__c, Opportunity.Account.Name,Scanning_Charges__c,Registration__c,Agreement_Value__c,Unit_Cost__c,Agreement_Value_w_o_Tax__c,Approved_Discount__c,Stamp_Duty__c,Project_Address__c,Tower__r.Name,Carpet_Area__c , Floor_No__c, Appt__c, Other_Charges_For_GST__c,TotalPrice,
                    (select Id, Product2.Saleable_Area__c, Floor_Rise_Charges__c,Development_Charges__c,TotalPrice ,Preferential_Location_charges__c,UnitPrice, Quantity, Product2.EVBT__c, Product2.Different_Unit_Area__c, Product2.Description, Product2.Family, Product2.Unit_Category__c, Product2.Carpet_Area_RERA_Carpet__c, Sub_Total__c from QuoteLineItems where (Product2.Family = 'Other Charges' OR Product2.Family = 'Saleable Unit' )) 
                    from Quote where Id =: parentId];
        system.debug('Inside initialiseList'+parentId+' :: lstQuote ::'+ lstQuote);
        if(lstQuote != null && !lstQuote.isEmpty()){
            List<QuoteLineItem> lstOtherChargesItem = new List<QuoteLineItem>();
            QuoteLineItem objSalesableUnitItem = new QuoteLineItem();
            pdfName = lstQuote[0].Name;
            // system.debug('lstQuote'+lstQuote[0].QuoteLineItems);
            for(QuoteLineItem objQuoteLineItem : lstQuote[0].QuoteLineItems){
                if(objQuoteLineItem.Product2.Family == 'Other Charges'){
                    lstOtherChargesItem.add(objQuoteLineItem);
                }else if(objQuoteLineItem.Product2.Family == 'Saleable Unit'){
                    objSalesableUnitItem = objQuoteLineItem;
                }
            }
            System.debug('Inside ');
            objPriceSheetWrapper = new PriceSheetWrapper(lstQuote[0], lstOtherChargesItem, objSalesableUnitItem);
        }
        
        //Payment_Plan__c objPaymentPlan = [select Id, Name from Payment_Plan__c where Quote__c =: parentId LIMIT 1];
        lstPaymentLine = new list<Payment_Plan_Line__c> ([Select id,Name, Payment_Plan__c, Title__c, Value__c, Amount_After_Tax__c  from Payment_Plan_Line__c where Payment_Plan__c = :paymentPlanId]);
    }
    /******************************************Wrapper Class**********************************/
    public class PriceSheetWrapper{
        public Quote objQuote{get;set;}
        public List<QuoteLineItem> lstQuoteLine{get;set;}
        public QuoteLineItem objSaleableUnit{get; set;}
        public PriceSheetWrapper(Quote objQuote, List<QuoteLineItem> lstQuoteLine, QuoteLineItem objSaleableUnit) {
            this.objQuote = objQuote;
            this.lstQuoteLine = lstQuoteLine;
            this.objSaleableUnit = objSaleableUnit;
        }
    }
    
}