force-app/main/default/objects/Module__c/fields/Facing__c.field-meta.xml
<CustomField>
    <fullName>Facing__c</fullName>
    <label>Facing</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup on Module__c . This is for Tower which will be displayed on Wing Record Type</description>
    <inlineHelpText>Select Tower</inlineHelpText>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Wings</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <description>Tower Name</description>
    <inlineHelpText>Enter Tower Name</inlineHelpText>
    <label>Tower Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Size__c.field-meta.xml
<CustomField>
    <fullName>Unit_Size__c</fullName>
    <description>Unit Size</description>
    <inlineHelpText>Select Unit Size</inlineHelpText>
    <label>Unit Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <description>Unit Status</description>
    <inlineHelpText>Select Unit Status</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Vastu__c.field-meta.xml
<CustomField>
    <fullName>Vastu__c</fullName>
    <label>Unit Vastu</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North-East</fullName>
            </value>
            <value>
                <fullName>North-West</fullName>
            </value>
            <value>
                <fullName>South-East</fullName>
            </value>
            <value>
                <fullName>South-West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing_Name__c.field-meta.xml
<CustomField>
    <fullName>Wing_Name__c</fullName>
    <description>Wing Name</description>
    <inlineHelpText>Enter Wing Name</inlineHelpText>
    <label>Wing Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Floor.recordType-meta.xml
<RecordType>
    <fullName>Floor</fullName>
    <active>true</active>
    <description>Record Type for Floor</description>
    <label>Floor</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Tower.recordType-meta.xml
<RecordType>
    <fullName>Tower</fullName>
    <active>true</active>
    <description>Record Type for Project Tower</description>
    <label>Tower</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>Record Type for Unit</description>
    <label>Unit</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Wing.recordType-meta.xml
<RecordType>
    <fullName>Wing</fullName>
    <active>true</active>
    <description>Record Type for Project Tower Wing</description>
    <label>Wing</label>
</RecordType>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>To capture the Project Status Green or Red, created for Nexus migration</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Used to have field values as Off plan, Completed and Ready.</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Off Plan</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/reimGetPicklistTypeFields.cls
public with sharing class reimGetPicklistTypeFields {


    @AuraEnabled(cacheable=true)
	public static List<String> getProjectTypeValues() {
    Set<String> typeValues = new Set<String>();
    Schema.DescribeFieldResult fieldResult = Project__c.Project_Type__c.getDescribe();
    List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
    for (Schema.PicklistEntry picklistVal : picklistValues) {
        typeValues.add(picklistVal.getLabel());
    }
    
    List<String> typeValuesLst=new List<String>(typeValues);
    typeValuesLst.add(0, 'All');
    system.debug('Project Type values: ' + typeValuesLst);
    return typeValuesLst;
}

    @AuraEnabled(cacheable=true)
    public static List<String> getProjectStatusValues() {
        List<String> statusValues = new List<String>();
        Schema.DescribeFieldResult fieldResult = Project__c.Project_Status__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry picklistVal : picklistValues) {
            statusValues.add(picklistVal.getLabel());
        }
 
		statusValues.add(0,'All');
        system.debug('Project Type values'+statusValues);
        return statusValues;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getDependentPicklistValues(String parentFieldName, String selectedParentValue, String dependentFieldName) {
        List<String> dependentValues = new List<String>();
        String soql = 'SELECT ' + dependentFieldName + ' FROM Project__c WHERE ' + parentFieldName + ' = \'' + selectedParentValue + '\'';
        List<Project__c> records = Database.query(soql);
        system.debug('Project Type values: ' + records);
        Set<String> sizeTypeValues = new Set<String>();
        for (Project__c record : records) {
            sizeTypeValues.add((String) record.get(dependentFieldName));
            system.debug('sizeTypeValues: ' + sizeTypeValues);
        }
        dependentValues.addAll(sizeTypeValues);
        system.debug('Project Type values: ' + dependentValues);
        return dependentValues;
}
    
     @AuraEnabled(cacheable=true)
    public static List<String> getProjectLocationValues() {
        List<Project__c> locationValues = [Select id, Project_Address__City__s from Project__c];
        List<String> locations=new List<String>();
        Map<String,Project__c> mapofLocationValues=new Map<String,Project__c>();

		for(Project__c loc:locationValues){
   	 	mapofLocationValues.put(loc.Project_Address__City__s,loc);//This is map and hence it will always have unique values 
		}
		system.debug('List return'+mapofLocationValues.keySet());
        locations.addAll(mapofLocationValues.keySet());
        locations.add(0,'All');
        System.debug(locations);
        return locations;
    }
    
    /*Dev:Sushant S
	  The Below code is written for Floor and Units page to fetch the option values for filters*/
     @AuraEnabled(cacheable=true)
    		public static List<Module__c> getTowersOptionsPerProject(String projId) {
         	List<Module__c> towerValues = new  List<Module__c>([Select Id,Tower_Name__c FROM Module__c where Project__c =:projId AND Record_Type_Name__c='Tower']);
        	system.debug(towerValues);
        	return towerValues;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getWingOptionsPerTowerOfProject(String towerId) {
        List<Module__c> wingValues = [Select Id,Wing_Name__c FROM Module__c where Tower__c =:towerId AND Record_Type_Name__c='Wing'];
        List<String> wings=new List<String>();
        Map<String,Module__c> mapofWingValues=new Map<String,Module__c>();

		for(Module__c mod : wingValues){
                mapofWingValues.put(mod.Wing_Name__c,mod);//This is map and hence it will always have unique values 
		}
		system.debug('List return'+mapofWingValues.keySet());
        wings.addAll(mapofWingValues.keySet());
        wings.add(0,'All');		//Adding 'All' value to the list
        System.debug(wings);
        return wings;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getUnitSizeOptionsPerTowerOfProject(String towerId) {
        List<Module__c> unitSizeValues = [Select Id,Tower__c, Unit_Size__c FROM Module__c where Tower__c =:towerId AND Record_Type_Name__c='Unit'];
        List<String> unitSize=new List<String>();
        Map<String,Module__c> mapofunitSizeValues=new Map<String,Module__c>();

		for(Module__c mod : unitSizeValues){
                mapofunitSizeValues.put(mod.Unit_Size__c ,mod);//This is map and hence it will always have unique values 
		}
		system.debug('List return'+mapofunitSizeValues.keySet());
        unitSize.addAll(mapofunitSizeValues.keySet());
        unitSize.add(0,'All');		//Adding 'All' value to the list
        System.debug(unitSize);
        return unitSize;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getFacingOptionsPerTowerOfProject(String towerId) {
        List<Module__c> FacingValues = [Select Id,Tower__c, facing__c FROM Module__c where Tower__c =:towerId AND Record_Type_Name__c='Unit'];
        List<String> Facing=new List<String>();
        Map<String,Module__c> mapofFacingValues=new Map<String,Module__c>();

		for(Module__c mod : FacingValues){
                mapofFacingValues.put(mod.Facing__c ,mod);//This is map and hence it will always have unique values 
		}
		system.debug('List return'+mapofFacingValues.keySet());
        Facing.addAll(mapofFacingValues.keySet());
        Facing.add(0,'All');		//Adding 'All' value to the list
        System.debug(Facing);
        return Facing;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getVastuOptionsPerTowerOfProject(String towerId) {
        List<Module__c> vastuValues = [Select Id,Tower__c, vastu__c FROM Module__c where Tower__c =:towerId AND Record_Type_Name__c='Unit'];
        List<String> vastu=new List<String>();
        Map<String,Module__c> mapofVastuValues=new Map<String,Module__c>();

		for(Module__c mod : vastuValues){
                mapofVastuValues.put(mod.vastu__c ,mod);//This is map and hence it will always have unique values 
		}
		system.debug('List return'+mapofVastuValues.keySet());
        vastu.addAll(mapofVastuValues.keySet());
        vastu.add(0,'All');		//Adding 'All' value to the list
        System.debug(vastu);
        return vastu;
    }
    
        @AuraEnabled(cacheable=true)
    public static List<String> getUnitStatusPerTowerOfProject(String towerId) {
        List<Module__c> unitStatusValues = [Select Id,Tower__c, Unit_Status__c FROM Module__c where Tower__c =:towerId AND Record_Type_Name__c='Unit'];
        List<String> unitStatus=new List<String>();
        Map<String,Module__c> mapofunitStatusValues=new Map<String,Module__c>();

		for(Module__c mod : unitStatusValues){
                mapofunitStatusValues.put(mod.Unit_Status__c ,mod);//This is map and hence it will always have unique values 
		}
		system.debug('List return'+mapofunitStatusValues.keySet());
        unitStatus.addAll(mapofunitStatusValues.keySet());
        unitStatus.add(0,'All');		//Adding 'All' value to the list
        System.debug(unitStatus);
        return unitStatus;
    }
    
}