force-app/main/default/objects/Module__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be displayed when Record type is unit, to select floor.This is self lookup</description>
    <inlineHelpText>Select Floor</inlineHelpText>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Floor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Modules2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/FloorPlan__c.field-meta.xml
<CustomField>
    <fullName>FloorPlan__c</fullName>
    <label>Units linked with Floor</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <description>Unit Name</description>
    <inlineHelpText>Enter Unit Name</inlineHelpText>
    <label>Unit Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Floor.recordType-meta.xml
<RecordType>
    <fullName>Floor</fullName>
    <active>true</active>
    <description>Record Type for Floor</description>
    <label>Floor</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>Record Type for Unit</description>
    <label>Unit</label>
</RecordType>

force-app/main/default/classes/Module_Trigger_Handler.cls
public class Module_Trigger_Handler {
    public static void update_unitsLinkedWithFloor(List<Module__c> lstUnits){
        String fp_value='';
        Set<ID> ids=new Set<ID>();
        for(Module__c mod:lstUnits){
            ids.add(mod.Floor__c);
        }
        
        List<Module__c> lstFloors=[Select id, FloorPlan__c from Module__c where Record_Type_Name__c='Floor' AND id=:ids];
        
        for(Module__c floors : lstFloors){
            fp_value=fp_value+floors.FloorPlan__c;
            for(Module__c units : lstUnits){
                if(floors.Id==units.Floor__c){
                    String name = units.Unit_Name__c;
					String result = name.substringAfter('Unit ');
                	fp_value=fp_value+result+', ';  
                }  
                floors.FloorPlan__c=fp_value.removeEnd(',');
            } 
            Database.update(lstFloors);
        }
        
    }
}