force-app/main/default/objects/Module__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be displayed when Record type is unit, to select floor.This is self lookup</description>
    <inlineHelpText>Select Floor</inlineHelpText>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Floor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Modules2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup on Module__c . This is for Tower which will be displayed on Wing Record Type</description>
    <inlineHelpText>Select Tower</inlineHelpText>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Wings</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <description>Tower Name</description>
    <inlineHelpText>Enter Tower Name</inlineHelpText>
    <label>Tower Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <description>Unit Name</description>
    <inlineHelpText>Enter Unit Name</inlineHelpText>
    <label>Unit Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing__c.field-meta.xml
<CustomField>
    <fullName>Wing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to show Wing when record Type is Floor. Self Lookup</description>
    <inlineHelpText>Select Wing</inlineHelpText>
    <label>Wing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Wing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Modules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Tower.recordType-meta.xml
<RecordType>
    <fullName>Tower</fullName>
    <active>true</active>
    <description>Record Type for Project Tower</description>
    <label>Tower</label>
</RecordType>

force-app/main/default/objects/Module__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>Record Type for Unit</description>
    <label>Unit</label>
</RecordType>

force-app/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>Project Address</description>
    <inlineHelpText>Enter Project Address</inlineHelpText>
    <label>Project Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Header__c.field-meta.xml
<CustomField>
    <fullName>Project_Header__c</fullName>
    <description>Project Header</description>
    <inlineHelpText>Enter Project Header</inlineHelpText>
    <label>Project Header</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Image__c.field-meta.xml
<CustomField>
    <fullName>Project_Image__c</fullName>
    <description>Add Project Image.</description>
    <inlineHelpText>Add Project Image.</inlineHelpText>
    <label>Project Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Location__c.field-meta.xml
<CustomField>
    <fullName>Project_Location__c</fullName>
    <description>Project Location</description>
    <inlineHelpText>Enter Project Location in Latitude and Longitude</inlineHelpText>
    <label>Project Location</label>
    <scale>3</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <description>To capture the Project Status Green or Red, created for Nexus migration</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Used to have field values as Off plan, Completed and Ready.</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Off Plan</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Size_Type__c.field-meta.xml
<CustomField>
    <fullName>Size_Type__c</fullName>
    <description>Size Type</description>
    <inlineHelpText>select Size Type</inlineHelpText>
    <label>Size Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Hospitality(Hotel,Motels,Resorts)</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>Bunglow</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Among Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Unit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/reimdisplayProjectsController.cls
public with sharing class reimdisplayProjectsController {


    //Display All project Records
    @AuraEnabled(cacheable=true)
    public static List<ProjectWithTowerCountWrapper> showProjects() {
        // Create a list to store the projects with tower and unit name count
        List<ProjectWithTowerCountWrapper> projectsWithTowerCount = new List<ProjectWithTowerCountWrapper>();
    
        // Query the Project__c object to retrieve project information
        List<Project__c> projects = [SELECT Id, Name, Project_Description__c, Project_Image__c, Project_Header__c, Project_Location__c,
                                     Project_Address__c, Project_Status__c, Project_Type__c, Size_Type__c
                                     FROM Project__c];
    
        // Iterate over the projects
        for (Project__c project : projects) {
            // Query the Module__c object to retrieve the count of towers associated with the project
            AggregateResult towerResult = [SELECT Count(Tower_Name__c) FROM Module__c WHERE Project__c = :project.Id];
            Integer towerCount = Integer.valueOf(towerResult.get('expr0'));
    
            // Query the Unit__c object to retrieve the count of unit names associated with the project
            AggregateResult unitResult = [SELECT Count(Unit_Name__c) FROM Module__c WHERE Floor__r.Wing__r.Tower__r.Project__c = :project.Id];
            Integer unitCount = Integer.valueOf(unitResult.get('expr0'));
    
            // Create a new ProjectWithTowerCountWrapper object and add it to the list
            projectsWithTowerCount.add(new ProjectWithTowerCountWrapper(project, towerCount, unitCount));
        }
    
        // Return the list of projects with tower and unit name count
        return projectsWithTowerCount;
    }
    
    public class ProjectWithTowerCountWrapper {
        @AuraEnabled
        public Project__c project;
        @AuraEnabled
        public Integer towerCount;
        @AuraEnabled
        public Integer unitCount;
    
        public ProjectWithTowerCountWrapper(Project__c project, Integer towerCount, Integer unitCount) {
            this.project = project;
            this.towerCount = towerCount;
            this.unitCount = unitCount;
        }
    }
    




    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProject(String recordId){
        String recId = recordId;
        try {
        return[select Id,Name,Project_Description__c,Project_Image__c,Project_Header__c,Project_Location__c,Project_Address__c,Project_Status__c, Project_Type__c,Size_Type__c
               from Project__c 
               where Id =: recId ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}