force-app/main/default/objects/Module__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be displayed when Record type is unit, to select floor.This is self lookup</description>
    <inlineHelpText>Select Floor</inlineHelpText>
    <label>Floor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Floor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Modules2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-Detail relation to Project</description>
    <inlineHelpText>Select Project</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers, Amenities, Specifications</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup on Module__c . This is for Tower which will be displayed on Wing Record Type</description>
    <inlineHelpText>Select Tower</inlineHelpText>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Wings</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <description>Tower Name</description>
    <inlineHelpText>Enter Tower Name</inlineHelpText>
    <label>Tower Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <description>Unit Name</description>
    <inlineHelpText>Enter Unit Name</inlineHelpText>
    <label>Unit Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <description>Unit Status</description>
    <inlineHelpText>Select Unit Status</inlineHelpText>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Wing__c.field-meta.xml
<CustomField>
    <fullName>Wing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to show Wing when record Type is Floor. Self Lookup</description>
    <inlineHelpText>Select Wing</inlineHelpText>
    <label>Wing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Wing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Modules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Tower.recordType-meta.xml
<RecordType>
    <fullName>Tower</fullName>
    <active>true</active>
    <description>Record Type for Project Tower</description>
    <label>Tower</label>
</RecordType>

force-app/main/default/classes/reimTowerUnitsCount.cls
public with sharing class reimTowerUnitsCount {
    
    @AuraEnabled(cacheable=true)
public static Integer getTowerCount(String ProjectId) {
    String proId= ProjectId;
    List<Module__c> modules = [SELECT Tower_Name__c FROM Module__c WHERE Project__c = :proId];
    
    Set<String> uniqueTowerNames = new Set<String>();
    for (Module__c module : modules) {
        if (module.Tower_Name__c != null) {
            uniqueTowerNames.add(module.Tower_Name__c);
        }
    }
    
    Integer towerCount = uniqueTowerNames.size();
    System.debug('Total Tower Names: ' + towerCount);
    return towerCount;
}


    @AuraEnabled(cacheable=true)
    public static Integer getUnitCount(String ProjectId) {
        String proId = ProjectId;
        AggregateResult[] results = [SELECT COUNT(Unit_Name__c) unitcnt FROM Module__c WHERE Floor__r.Wing__r.Tower__r.Project__c=:proId  GROUP BY Floor__r.Wing__r.Tower__r.Project__c];
        
        if (results.size() > 0) {
            Integer modUnitCount = (Integer)results[0].get('unitcnt');
           
            System.debug('Total Units are: ' + modUnitCount);
            return modUnitCount;
        }
        
        return 0; // Return 0 if no results are found
    }
    @AuraEnabled(cacheable=true)
    public static Integer getSoldUnitCount(String ProjectId) {
        String proId = ProjectId;
        String Status = 'Sold';
        AggregateResult[] results = [SELECT COUNT(Unit_Name__c) unitcnt	 FROM Module__c WHERE Floor__r.Wing__r.Tower__r.Project__c=:proId AND Unit_Status__c=:Status  GROUP BY Floor__r.Wing__r.Tower__r.Project__c];
        
        if (results.size() > 0) {
            Integer modSoldUnitCount = (Integer)results[0].get('unitcnt');
           
            System.debug('Total Sold Units are: ' + modSoldUnitCount);
            return modSoldUnitCount;
        }
        
        return 0; // Return 0 if no results are found
    }
    @AuraEnabled(cacheable=true)
    public static Integer getAvlUnitCount(String ProjectId) {
        String proId = ProjectId;
        String Status = 'Available';
        AggregateResult[] results = [SELECT COUNT(Unit_Name__c) unitcnt	 FROM Module__c WHERE Floor__r.Wing__r.Tower__r.Project__c=:proId AND Unit_Status__c=:Status  GROUP BY Floor__r.Wing__r.Tower__r.Project__c];
        
        if (results.size() > 0) {
            Integer modAvlUnitCount = (Integer)results[0].get('unitcnt');
           
            System.debug('Total Available Units are: ' + modAvlUnitCount);
            return modAvlUnitCount;
        }
        
        return 0; // Return 0 if no results are found
    }
}